// <auto-generated/>
// The exercise of every lowered family without a hand-written one: each mapped method called once with fixed inputs, its result printed as hex bytes; real .NET is the oracle.
// Generated by tools/gen-isa-map from System.Private.CoreLib; regenerate with
//   dotnet run tools/gen-isa-map/gen-isa-map.cs -- --corelib <System.Private.CoreLib.dll>
using System;
using System.Collections.Generic;
using System.Runtime.Intrinsics;
using Arm = System.Runtime.Intrinsics.Arm;
using Wasm = System.Runtime.Intrinsics.Wasm;
using X86 = System.Runtime.Intrinsics.X86;

namespace PlatformIsaProbe;

internal static class Exercises
{
    internal static void RegisterX86(Dictionary<string, Action> exercises)
    {
    }

    internal static void RegisterArm(Dictionary<string, Action> exercises)
    {
        exercises["Arm.Aes"] = ArmAes;
        exercises["Arm.Sha1"] = ArmSha1;
        exercises["Arm.Sha256"] = ArmSha256;
    }

    internal static void RegisterWasm(Dictionary<string, Action> exercises)
    {
    }

    private static unsafe void ArmAes()
    {
        Console.WriteLine("Decrypt(v128u8,v128u8)=" + Fmt.Hex(Arm.Aes.Decrypt(Vector128.Create((byte)36, (byte)73, (byte)110, (byte)147, (byte)184, (byte)221, (byte)2, (byte)39, (byte)76, (byte)113, (byte)150, (byte)187, (byte)224, (byte)5, (byte)42, (byte)79), Vector128.Create((byte)65, (byte)102, (byte)139, (byte)176, (byte)213, (byte)250, (byte)31, (byte)68, (byte)105, (byte)142, (byte)179, (byte)216, (byte)253, (byte)34, (byte)71, (byte)108)).AsByte()));
        Console.WriteLine("Encrypt(v128u8,v128u8)=" + Fmt.Hex(Arm.Aes.Encrypt(Vector128.Create((byte)36, (byte)73, (byte)110, (byte)147, (byte)184, (byte)221, (byte)2, (byte)39, (byte)76, (byte)113, (byte)150, (byte)187, (byte)224, (byte)5, (byte)42, (byte)79), Vector128.Create((byte)65, (byte)102, (byte)139, (byte)176, (byte)213, (byte)250, (byte)31, (byte)68, (byte)105, (byte)142, (byte)179, (byte)216, (byte)253, (byte)34, (byte)71, (byte)108)).AsByte()));
        Console.WriteLine("InverseMixColumns(v128u8)=" + Fmt.Hex(Arm.Aes.InverseMixColumns(Vector128.Create((byte)36, (byte)73, (byte)110, (byte)147, (byte)184, (byte)221, (byte)2, (byte)39, (byte)76, (byte)113, (byte)150, (byte)187, (byte)224, (byte)5, (byte)42, (byte)79)).AsByte()));
        Console.WriteLine("MixColumns(v128u8)=" + Fmt.Hex(Arm.Aes.MixColumns(Vector128.Create((byte)36, (byte)73, (byte)110, (byte)147, (byte)184, (byte)221, (byte)2, (byte)39, (byte)76, (byte)113, (byte)150, (byte)187, (byte)224, (byte)5, (byte)42, (byte)79)).AsByte()));
        Console.WriteLine("PolynomialMultiplyWideningLower(v64i64,v64i64)=" + Fmt.Hex(Arm.Aes.PolynomialMultiplyWideningLower(Vector64.Create(4828507740108L), Vector64.Create(8718138975195L)).AsByte()));
        Console.WriteLine("PolynomialMultiplyWideningLower(v64u64,v64u64)=" + Fmt.Hex(Arm.Aes.PolynomialMultiplyWideningLower(Vector64.Create(4828507740108UL), Vector64.Create(8718138975195UL)).AsByte()));
        Console.WriteLine("PolynomialMultiplyWideningUpper(v128i64,v128i64)=" + Fmt.Hex(Arm.Aes.PolynomialMultiplyWideningUpper(Vector128.Create(4828507740108L, 9791140695219L), Vector128.Create(8718138975195L, 13680771930306L)).AsByte()));
        Console.WriteLine("PolynomialMultiplyWideningUpper(v128u64,v128u64)=" + Fmt.Hex(Arm.Aes.PolynomialMultiplyWideningUpper(Vector128.Create(4828507740108UL, 9791140695219UL), Vector128.Create(8718138975195UL, 13680771930306UL)).AsByte()));
    }

    private static unsafe void ArmSha1()
    {
        Console.WriteLine("FixedRotate(v64u32)=" + Fmt.Hex(Arm.Sha1.FixedRotate(Vector64.Create(4604796U, 9337503U)).AsByte()));
        Console.WriteLine("HashUpdateChoose(v128u32,v64u32,v128u32)=" + Fmt.Hex(Arm.Sha1.HashUpdateChoose(Vector128.Create(4604796U, 9337503U, 14070210U, 18802917U), Vector64.Create(8314215U, 13046922U), Vector128.Create(12023634U, 16756341U, 21489048U, 26221755U)).AsByte()));
        Console.WriteLine("HashUpdateMajority(v128u32,v64u32,v128u32)=" + Fmt.Hex(Arm.Sha1.HashUpdateMajority(Vector128.Create(4604796U, 9337503U, 14070210U, 18802917U), Vector64.Create(8314215U, 13046922U), Vector128.Create(12023634U, 16756341U, 21489048U, 26221755U)).AsByte()));
        Console.WriteLine("HashUpdateParity(v128u32,v64u32,v128u32)=" + Fmt.Hex(Arm.Sha1.HashUpdateParity(Vector128.Create(4604796U, 9337503U, 14070210U, 18802917U), Vector64.Create(8314215U, 13046922U), Vector128.Create(12023634U, 16756341U, 21489048U, 26221755U)).AsByte()));
        Console.WriteLine("ScheduleUpdate0(v128u32,v128u32,v128u32)=" + Fmt.Hex(Arm.Sha1.ScheduleUpdate0(Vector128.Create(4604796U, 9337503U, 14070210U, 18802917U), Vector128.Create(8314215U, 13046922U, 17779629U, 22512336U), Vector128.Create(12023634U, 16756341U, 21489048U, 26221755U)).AsByte()));
        Console.WriteLine("ScheduleUpdate1(v128u32,v128u32)=" + Fmt.Hex(Arm.Sha1.ScheduleUpdate1(Vector128.Create(4604796U, 9337503U, 14070210U, 18802917U), Vector128.Create(8314215U, 13046922U, 17779629U, 22512336U)).AsByte()));
    }

    private static unsafe void ArmSha256()
    {
        Console.WriteLine("HashUpdate1(v128u32,v128u32,v128u32)=" + Fmt.Hex(Arm.Sha256.HashUpdate1(Vector128.Create(4604796U, 9337503U, 14070210U, 18802917U), Vector128.Create(8314215U, 13046922U, 17779629U, 22512336U), Vector128.Create(12023634U, 16756341U, 21489048U, 26221755U)).AsByte()));
        Console.WriteLine("HashUpdate2(v128u32,v128u32,v128u32)=" + Fmt.Hex(Arm.Sha256.HashUpdate2(Vector128.Create(4604796U, 9337503U, 14070210U, 18802917U), Vector128.Create(8314215U, 13046922U, 17779629U, 22512336U), Vector128.Create(12023634U, 16756341U, 21489048U, 26221755U)).AsByte()));
        Console.WriteLine("ScheduleUpdate0(v128u32,v128u32)=" + Fmt.Hex(Arm.Sha256.ScheduleUpdate0(Vector128.Create(4604796U, 9337503U, 14070210U, 18802917U), Vector128.Create(8314215U, 13046922U, 17779629U, 22512336U)).AsByte()));
        Console.WriteLine("ScheduleUpdate1(v128u32,v128u32,v128u32)=" + Fmt.Hex(Arm.Sha256.ScheduleUpdate1(Vector128.Create(4604796U, 9337503U, 14070210U, 18802917U), Vector128.Create(8314215U, 13046922U, 17779629U, 22512336U), Vector128.Create(12023634U, 16756341U, 21489048U, 26221755U)).AsByte()));
    }

}
