#!/usr/bin/env bash
# CRI ADX LE Android E2E gate: the CriWare GodotSampleApp — a real C# Godot game
# driving the proprietary CRI Atom audio engine through ~980 [DllImport]s on
# module "cri_atom" — goes through the dn2cpp mono-module Android lane.
#
# The staged project is the adjacent cri_adx_le_for_csharp sample, patched the
# way the editor-export gates patch theirs (a copy, never the source tree): the
# TFM moves to the net9.0 the stock Android template validates, and an
# AutoVerify autoload is injected that runs the sample's audio path unattended
# — version string, cue Start(), playback status polling, error-callback latch
# — and prints CRI_E2E_* markers, because on a device there is no diff-able
# stdout, only logcat.
#
# The managed CriWare.CriAtomLE.dll is the package's ANDROID flavor, swapped in
# by explicit path: the package selects flavors strictly by RuntimeIdentifier
# machinery, and a plain (host-RID) build resolves the desktop one. The
# transpile itself is the cross-assembly P/Invoke opt-in end to end:
# --pinvoke-module cri_atom lowers a referenced assembly's imports to direct
# native calls and lands the module in pinvoke-libs.txt, where the CMake app
# link picks it up as -lcri_atom.
#
# Requires the CriWare.CriAtomLE NuGet package + sample repository (resolved by
# the cri_* helpers in _common.sh) and the fork editor cache; each absence is a
# gate_skip, never a silent pass.
source "$(dirname "$0")/_common.sh"
source "$(dirname "$0")/_godot_fork.sh"

OUT=gates/out-cri-android
PROJECT_NAME=GodotSampleApp

godot_fork_preflight
CRI_MANAGED_ANDROID="$(cri_managed_dll android)" \
    || gate_skip "CriWare.CriAtomLE package (android flavor) not present — see cri_nuget_root in gates/_common.sh"
# bash 3.2 (no mapfile): read the all-or-nothing list line by line.
CRI_NATIVE_SOS=()
while IFS= read -r _so; do CRI_NATIVE_SOS+=("$_so"); done < <(cri_android_native_files)
[ "${#CRI_NATIVE_SOS[@]}" -eq 3 ] \
    || gate_skip "CriWare.CriAtomLE android-arm64 native .so set not present"
CRI_SAMPLE_ROOT="$(cri_sample_root)" \
    || gate_skip "cri_adx_le_for_csharp sample repository not present"
SAMPLE_SRC="$CRI_SAMPLE_ROOT/samples/GodotSampleApp"
EXT_SRC="$CRI_SAMPLE_ROOT/samples/SampleExtensions"
[ -d "$SAMPLE_SRC" ] && [ -d "$EXT_SRC" ] \
    || gate_skip "GodotSampleApp/SampleExtensions not found under $CRI_SAMPLE_ROOT"
if [ -z "${ANDROID_NDK_ROOT:-}" ] || [ ! -f "$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" ]; then
    gate_skip "no Android NDK under ANDROID_NDK_ROOT — the drop-in cannot be cross-compiled"
fi
CRI_NATIVE_DIR="$(dirname "${CRI_NATIVE_SOS[0]}")"

echo "== 1/6 Fork pin + interop-ABI tripwire =="
godot_fork_pin_abi_check

echo "== 2/6 Staging the sample project =="
# Copied, never exported in place: the source tree is a foreign repository this
# gate must not perturb, and every patch below applies to the copy alone.
STAGE="$OUT/stage"
PROJ="$STAGE/GodotSampleApp"
rm -rf "$STAGE"
mkdir -p "$STAGE"
cp -R "$SAMPLE_SRC" "$PROJ"
cp -R "$EXT_SRC" "$STAGE/SampleExtensions"
rm -rf "$PROJ/.godot" "$PROJ/bin" "$PROJ/obj" \
       "$STAGE/SampleExtensions/bin" "$STAGE/SampleExtensions/obj"

# The TFM moves to net9.0 — a template (non-gradle) Android export validates the
# C# project's TFM against exactly net9.0 before it runs a single step (the same
# constraint the editor-export Android gate documents; it is the template's, not
# dn2cpp's). Both rewrites replace whatever the sample carries rather than one
# named version: this is a THIRD-PARTY project pinned to the Godot it shipped
# against (4.2.1 / net7.0 on upstream master today), and nothing makes that track
# ours — a rewrite keyed on the value it expects to find is a no-op against a
# pristine clone, and then the assert below fails on a perfectly normal checkout.
# The TFM pattern matches the ATTRIBUTE-LESS element only, leaving the sample's
# `<TargetFramework Condition="...ios...">` line alone, which is the point of not
# using a global version substitution here.
SDK_VERSION="$(godot_nuget_sdk_version "$FORK_ROOT/nuget")"
csproj_tmp="$(mktemp)"
sed -e "s|Sdk=\"Godot.NET.Sdk/[^\"]*\"|Sdk=\"Godot.NET.Sdk/$SDK_VERSION\"|" \
    -e 's|<TargetFramework>net[0-9][0-9.]*</TargetFramework>|<TargetFramework>net9.0</TargetFramework>|' \
    "$PROJ/$PROJECT_NAME.csproj" > "$csproj_tmp"
mv "$csproj_tmp" "$PROJ/$PROJECT_NAME.csproj"
grep -q "Godot.NET.Sdk/$SDK_VERSION" "$PROJ/$PROJECT_NAME.csproj" \
    || { echo "FAIL: could not re-pin the staged project onto the fork feed's Godot.NET.Sdk $SDK_VERSION" >&2; exit 1; }
grep -q "<TargetFramework>net9.0</TargetFramework>" "$PROJ/$PROJECT_NAME.csproj" \
    || { echo "FAIL: could not retarget the staged project at net9.0" >&2; exit 1; }

cat > "$PROJ/nuget.config" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by gates/build-and-run-cri-android.sh — do not commit.
     Points the Godot.NET.Sdk resolver + restore at the fork's local feed; the
     CriWare.CriAtomLE package resolves from the global packages cache. The feed
     path is native (godot_fork_native_path): MSYS converts a path it hands a
     native program as an ARGUMENT, never one written into a file, so an MSYS
     /c/... here reaches NuGet as C:\c\Users\... and restore fails on a feed
     that "does not exist". -->
<configuration>
  <packageSources>
    <clear />
    <add key="dn2cpp-godot-fork-local" value="$(godot_fork_native_path "$FORK_ROOT/nuget")" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
EOF

# The unattended run: the sample's own SampleScript._Ready wires the Godot
# FileAccess IoInterface and loads the ACF/ACB from res://; this autoload then
# drives the same preview player the UI buttons drive, and prints markers the
# device section greps out of logcat. The playback status poll is what stands
# in for audibility: Playing means the voice pool allocated a voice and the
# output stream is being rendered into, which no headless assert can hear.
cat > "$PROJ/script/AutoVerify.cs" <<'EOF'
using Godot;
using System;
using System.Linq;
using CriWare;

// GENERATED by gates/build-and-run-cri-android.sh — do not commit.
// Unattended E2E driver: prints CRI_E2E_* markers for the gate to assert from
// logcat, then quits the game so the device run ends deterministically.
public partial class AutoVerify : Node
{
    private IDisposable _errorHandler;
    private bool _errored;
    private bool _started;
    private bool _sawPlaying;
    private int _frames;
    private int _playFrames;
    private CriAtomExPlayback _playback;

    public override void _Ready()
    {
        _errorHandler = CriBaseCSharp.ErrorCallback.RegisterListener(msg =>
        {
            // CRI message ids carry their severity as the first letter
            // ("W2021020900:..." vs "E..."): a warning (the Android hardware-
            // property hint, the pthread scheduling note) must not fail the run.
            if (msg != null && msg.StartsWith("W", StringComparison.Ordinal))
            {
                GD.Print("CRI_E2E_WARN " + msg);
                return;
            }
            _errored = true;
            GD.Print("CRI_E2E_ERROR " + msg);
        }, false);
        GD.Print("CRI_E2E_BOOT");
    }

    public override void _Process(double delta)
    {
        _frames++;
        try
        {
            Drive();
        }
        catch (Exception e)
        {
            GD.Print("CRI_E2E_EXCEPTION " + e);
            GD.Print("CRI_E2E_DONE");
            GetTree().Quit(1);
        }
    }

    private void Drive()
    {
        if (!_started)
        {
            // The main scene's SampleScript._Ready has run long before frame 30;
            // by then the ACF/ACB are loaded through the Godot FileAccess
            // IoInterface and the preview player is initialized.
            if (_frames < 30)
                return;
            _started = true;
            GD.Print("CRI_E2E_VERSION " + CriAtom.GetVersionString());
            var infos = CriAtomPreviewPlayer.Instance.GetCurrentCueInfoList().ToArray();
            GD.Print("CRI_E2E_CUES " + infos.Length);
            int cueId = infos.Length > 0 ? infos[0].id : 0;
            _playback = CriAtomPreviewPlayer.Instance.Play(cueId);
            GD.Print("CRI_E2E_PLAY_STARTED cue=" + cueId);
            return;
        }
        _playFrames++;
        var status = _playback.GetStatus();
        if (!_sawPlaying && status == CriAtomExPlayback.Status.Playing)
        {
            _sawPlaying = true;
            GD.Print("CRI_E2E_PLAYING");
        }
        // ~3 s at 60 fps: enough for the streaming voice to reach Playing and
        // render audibly, short enough for an automated device run.
        if (_playFrames >= 180)
        {
            GD.Print("CRI_E2E_RESULT playing=" + _sawPlaying + " status=" + status
                + " errors=" + _errored);
            GD.Print("CRI_E2E_DONE");
            GetTree().Quit();
        }
    }

    public override void _ExitTree()
    {
        _errorHandler?.Dispose();
        _errorHandler = null;
    }
}
EOF

# Registered as an autoload so no scene edit is needed; the sample's own
# MainScene stays the entry scene and keeps exercising its UI path. The
# [dotnet] append re-opens the sample's existing section (Godot's ConfigFile
# merges repeated headers) to add the fork exporter's knobs: extra_transpile_args
# is how --pinvoke-module cri_atom reaches the editor-driven transpile, and
# extra_link_flags is how the CRI link inputs reach the drop-in link — the -L
# pointing pinvoke-libs.txt's -lcri_atom at the package's android-arm64 native
# directory, plus -lcri_ware_android_le for the engine library the facade only
# DT_NEEDs (see the section-4 comment). The exporter passes the setting as
# -DDN2CPP_APP_LINK_FLAGS on every configure of its persistent build slot.
# $CRI_NATIVE_DIR is routed through godot_fork_native_path: this is a value
# written into project.godot, which no argument-conversion rule ever reaches
# (MSYS converts an argument it hands a native program, never a byte written
# into a file), so leaving it as MSYS's /c/... spelling would be unconditionally
# wrong, not merely at risk the way the multi-flag link strings elsewhere are.
# The addon enable wires the export plugin below into the headless export.
cat >> "$PROJ/project.godot" <<EOF

[autoload]

AutoVerify="*res://script/AutoVerify.cs"

[dotnet]

dn2cpp/extra_transpile_args=PackedStringArray("--pinvoke-module", "cri_atom")
dn2cpp/extra_link_flags=PackedStringArray("-L$(godot_fork_native_path "$CRI_NATIVE_DIR")", "-lcri_ware_android_le")

[editor_plugins]

enabled=PackedStringArray("res://addons/cri_export/plugin.cfg")
EOF

# The CRI native libraries enter the APK through a project-local
# EditorExportPlugin: add_shared_object() is the official route for an addon to
# ship extra native libraries, the exact path the platform exporter already
# takes for the drop-in itself — no fork change involved. The absolute package
# paths are machine-specific, so the addon is generated here, never committed.
mkdir -p "$PROJ/addons/cri_export"
cat > "$PROJ/addons/cri_export/plugin.cfg" <<'EOF'
[plugin]

name="cri_export"
description="Bundles the CRI ADX LE android-arm64 native libraries into the Android export (GENERATED by gates/build-and-run-cri-android.sh)"
author="dn2cpp"
version="1.0"
script="plugin.gd"
EOF
cat > "$PROJ/addons/cri_export/plugin.gd" <<'EOF'
@tool
extends EditorPlugin

var _export_plugin

func _enter_tree():
	_export_plugin = preload("res://addons/cri_export/cri_export_plugin.gd").new()
	add_export_plugin(_export_plugin)

func _exit_tree():
	remove_export_plugin(_export_plugin)
	_export_plugin = null
EOF
{
    printf '@tool\nextends EditorExportPlugin\n\n'
    printf 'const CRI_LIBS = [\n'
    for _so in "${CRI_NATIVE_SOS[@]}"; do
        printf '\t"%s",\n' "$_so"
    done
    printf ']\n\n'
    printf 'func _get_name() -> String:\n\treturn "CriNativeLibs"\n\n'
    printf 'func _export_begin(features: PackedStringArray, is_debug: bool, path: String, flags: int) -> void:\n'
    printf '\tif not features.has("android"):\n\t\treturn\n'
    printf '\tfor lib in CRI_LIBS:\n'
    printf '\t\tadd_shared_object(lib, PackedStringArray(["arm64-v8a"]), "")\n'
} > "$PROJ/addons/cri_export/cri_export_plugin.gd"

# The export preset: the stock-template (non-gradle) Android export against
# dotnet/export_backend = 2 (dn2cpp), arm64-v8a alone — the one ABI the backend
# builds. Modeled on the editor-export Android gate's preset.
cat > "$PROJ/export_presets.cfg" <<'EOF'
[preset.0]

name="dn2cpp-android"
platform="Android"
runnable=true
advanced_options=false
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter="*.acb,*.acf,*.awb"
exclude_filter=""
export_path=""
patches=PackedStringArray()
encryption_include_filters=""
encryption_exclude_filters=""
seed=0
encrypt_pck=false
encrypt_directory=false
script_export_mode=2

[preset.0.options]

gradle_build/use_gradle_build=false
architectures/armeabi-v7a=false
architectures/arm64-v8a=true
architectures/x86=false
architectures/x86_64=false
package/unique_name="com.criware.godotsampleapp"
package/name="GodotSampleApp"
dotnet/include_scripts_content=false
dotnet/include_debug_symbols=false
dotnet/export_backend=2
EOF

echo "== 3/6 Transpiling with --pinvoke-module cri_atom (android-flavor managed DLL) =="
build_proj src/Dn2Cpp.Cli/Dn2Cpp.Cli.csproj
dotnet build "$PROJ/$PROJECT_NAME.csproj" -c ExportRelease --nologo -v q
APPDIR="$PROJ/.godot/mono/temp/bin/ExportRelease"
[ -f "$APPDIR/$PROJECT_NAME.dll" ] || { echo "FAIL: not built: $APPDIR/$PROJECT_NAME.dll" >&2; exit 1; }

# The android-flavor swap. A host build resolves the package's desktop flavor
# (lib/net7.0/); the android flavor (runtimes/android/lib/net7.0/, compiled
# under the android define — InitializePlatform routes to InitializeANDROID) is
# what the device runs, so it is what the transpile must see.
cp -f "$CRI_MANAGED_ANDROID" "$APPDIR/CriWare.CriAtomLE.dll"

# Pin net10.0 (the JSON/measure gates' rule) and reference the fork editor's
# own GodotSharp, exactly as the fork's Dn2CppExporter does; the dependency
# order (CriWare before SampleExtensions) mirrors its sorted dependency walk.
#
# ANDROID-flavour CoreLib, not the host's — section 4 cross-links what this
# transpiles. On a POSIX host the two coincide and this is resolve_net10_corelib
# verbatim; on Windows they do not, and the host CoreLib's FileStream internals
# reach the NDK link as literal kernel32/ntdll P/Invokes (see
# locate_corelib_cross_posix in gates/_common.sh for the full shape).
corelib=$(locate_corelib_cross_posix net10)
GEN="$OUT/gen"
rm -rf "$GEN"
invoke_cli "$APPDIR/$PROJECT_NAME.dll" --dotnet-module \
    -r "$corelib" \
    -r "$FORK_GODOTSHARP/Api/Release/GodotSharp.dll" \
    -r "$APPDIR/CriWare.CriAtomLE.dll" \
    -r "$APPDIR/SampleExtensions.dll" \
    --auto-ref \
    --pinvoke-module cri_atom \
    -o "$GEN"

# The whole point of the opt-in: the module reaches the link manifest, where
# the CMake app build turns it into -lcri_atom. Exactly this one module — a
# second line would mean an import this gate does not link against.
[ -f "$GEN/pinvoke-libs.txt" ] \
    || { echo "FAIL: the transpile emitted no pinvoke-libs.txt" >&2; exit 1; }
printf 'cri_atom\n' | diff -u - <(strip_cr_win_file "$GEN/pinvoke-libs.txt") \
    || { echo "FAIL: pinvoke-libs.txt is not exactly 'cri_atom'" >&2; exit 1; }
echo "transpile OK: pinvoke-libs.txt = cri_atom"

# Export-stack + device probes, resolved here because they are cache-key terms:
# completing the stack (or attaching a device) later must move the key and
# force a live re-run of the sections it unlocks. All three probes are per-OS and
# all three live in _common.sh (android_ensure_java / android_sdk_root /
# android_editor_java_sdk), because this
# gate asks them TWICE — here for the key, and again at the APK tail — and the
# copy written out at each site is what left the pair macOS-only: a Windows box
# with Android Studio and the SDK in their ordinary places answered "no" to
# both, and the gate recorded a partial it had no reason to take.
JAVA_OK=no
android_ensure_java && JAVA_OK=yes
# A THIRD probe, and a distinct question from JAVA_OK's: Godot's Android exporter
# never looks at PATH — can_export reads the editor's export/android/java_sdk_path
# and refuses the preset when it is empty. So a box whose PATH `java` IS the JBR
# still fails the export, which is how this gate died inside the engine rather than
# recording a partial. Provisioned by gates/setup-android-export.sh.
EDITOR_JDK_OK=no
android_editor_java_sdk "$FORK_EDITOR" >/dev/null && EDITOR_JDK_OK=yes
_ver="$(godot_template_version_dir "$FORK_EDITOR" || true)"
ANDROID_TEMPLATE="$(godot_user_data_dir)/export_templates/$_ver/android_debug.apk"
SDK_OK=no
android_sdk_root >/dev/null && SDK_OK=yes
android_ensure_adb || true
SERIAL="${DN2CPP_ANDROID_SERIAL:-$(android_first_device)}"

# Cache: keyed on the transpile surface just emitted into $GEN plus every input
# the later sections consume — the fork context (pins, editor, GodotTools
# content), the NDK, the stock template, the CRI package artifacts, the
# self-hosted CLI the export toolchain packages, the runtime sources the drop-in
# compiles against, and the sample tree the pck packs. A partial (missing
# export stack / no device) is recorded as partial and re-run live under
# DN2CPP_REQUIRE_ALL=1, like every gate.
if gate_cache_check "$GEN" \
    "cri-android|$(godot_fork_ctx)|ndk=$ANDROID_NDK_ROOT|ndkver=$(file_text "$ANDROID_NDK_ROOT/source.properties" 2)|tmpl=$(file_sig "$ANDROID_TEMPLATE")|sdk=$SDK_OK|java=$JAVA_OK|editorjdk=$EDITOR_JDK_OK|device=${SERIAL:-none}|cri=$CRI_ATOM_VERSION|crimanaged=$(file_sig "$CRI_MANAGED_ANDROID")|crinative=$(file_sig "${CRI_NATIVE_SOS[0]}")+$(file_sig "${CRI_NATIVE_SOS[1]}")+$(file_sig "${CRI_NATIVE_SOS[2]}")" \
    "$SELFHOST_BIN" \
    dist/package-toolchain.sh \
    runtime \
    "$SAMPLE_SRC" \
    "$EXT_SRC"; then
    { gate_cache_hit_msg; exit 0; }
fi

echo "== 4/6 Cross-building the drop-in (NDK) against the CRI libraries =="
# pinvoke-libs.txt puts -lcri_atom on the app link; the -L pointing it at the
# package's android-arm64 native directory rides DN2CPP_APP_LINK_FLAGS —
# together with -lcri_ware_android_le, because the split is not what the module
# name suggests: libcri_atom.so is a thin facade (JNI_OnLoad + the
# underscore-suffixed SetDefaultConfig inline shims, 81 exports) and the whole
# criAtom*/criErr*/criFs* engine surface lives in libcri_ware_android_le.so,
# which the facade only DT_NEEDs. The Android link runs with --no-undefined, so
# both must be on the link line. The result is the dependency shape the APK
# ships: the drop-in DT_NEEDs both sonames, resolved out of lib/arm64-v8a/.
DROPIN="$OUT/lib$PROJECT_NAME.so"
# $CRI_NATIVE_DIR is routed through native_path (_common.sh): this string
# holds TWO flags, exactly the shape MSYS's own single-token argument
# conversion does not reach, so left as MSYS's /c/... spelling the NDK
# linker would fail to find -lcri_ware_android_le with no hint the cause is
# the path dialect rather than a missing library.
DN2CPP_EXTRA_LINK_FLAGS="-L$(native_path "$CRI_NATIVE_DIR") -lcri_ware_android_le" \
    compile_dotnet_module_android "$GEN" "$DROPIN"
desc="$(file -b "$DROPIN")"
printf '%s: %s\n' "$DROPIN" "$desc"
case "$desc" in
    *ELF*64-bit*aarch64*|*ELF*64-bit*ARM\ aarch64*) ;;
    *) echo "FAIL: the drop-in is not an ELF 64-bit aarch64 shared object" >&2; exit 1 ;;
esac
LLVM_NM="$(android_llvm_nm)" \
    || { echo "FAIL: no llvm-nm under $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/*/bin" >&2; exit 1; }
# Beside llvm-nm, so it carries the same $EXE_EXT: on a Windows host the NDK ships
# llvm-readelf.exe, and a bare name fails the -x test even though the tool is there.
LLVM_READELF="$(dirname "$LLVM_NM")/llvm-readelf$EXE_EXT"
[ -x "$LLVM_READELF" ] \
    || { echo "FAIL: no llvm-readelf beside $LLVM_NM" >&2; exit 1; }
# Snapshot to a file, then grep it (the SIGPIPE-under-pipefail discipline every
# ELF-inspecting gate follows).
DYN="$OUT/dropin-dynamic.txt"
"$LLVM_READELF" -d "$DROPIN" > "$DYN"
for lib in libcri_atom.so libcri_ware_android_le.so; do
    grep -q "NEEDED.*$lib" "$DYN" \
        || { echo "FAIL: the drop-in does not DT_NEED $lib" >&2; cat "$DYN" >&2; exit 1; }
done
"$LLVM_NM" -D --defined-only "$DROPIN" | grep "godotsharp_game_main_init" >/dev/null \
    || { echo "FAIL: the drop-in does not export godotsharp_game_main_init" >&2; exit 1; }
echo "cross-build OK: aarch64 drop-in, DT_NEEDED libcri_atom.so + libcri_ware_android_le.so, godotsharp_game_main_init exported"

# ── The APK tail: fork editor headless export ─────────────────────────────────
# Everything below needs the full Android export stack — the stock mono Android
# template, an Android SDK, a working JDK. The same two _common.sh probes the
# cache key above asked; asking them again (rather than reusing SDK_OK/JAVA_OK)
# is what re-applies android_ensure_java's PATH edit after the sections between,
# and re-asking is free.
# A missing piece is a PARTIAL, not a skip: sections 1-4 ran and asserted.
_ver="$(godot_template_version_dir "$FORK_EDITOR" || true)"
ANDROID_TEMPLATE="$(godot_user_data_dir)/export_templates/$_ver/android_debug.apk"
if [ ! -f "$ANDROID_TEMPLATE" ] \
    || ! android_sdk_root >/dev/null \
    || ! android_ensure_java \
    || ! android_editor_java_sdk "$FORK_EDITOR" >/dev/null; then
    gate_partial "Android export stack incomplete (official mono template / SDK / JDK on PATH / the editor's export/android/java_sdk_path — run gates/setup-android-export.sh) — APK export section skipped"
    gate_cache_commit
    echo "OK"
    exit 0
fi

echo "== 5/6 Exporting the APK (fork editor, dotnet/export_backend = dn2cpp) =="
stage_editor_toolchain "$FORK_GODOTSHARP" "$SELFHOST_BIN" "$OUT/package.log"

# The first import may abort in editor doc-gen teardown (Godot headless bug,
# harmless); tolerate a non-zero exit.
run_with_watchdog 600 "$FORK_EDITOR" --headless \
    --path "$PWD/$PROJ" --import >"$OUT/import.log" 2>&1 || true

# The CRI link flags ride the dotnet/dn2cpp/extra_link_flags project setting
# written above: the exporter passes it as -DDN2CPP_APP_LINK_FLAGS on EVERY
# configure of its persistent build slot, empty when unset — so the setting is
# the whole channel, and seeding the slot's CMake cache by hand would be
# overwritten. ($ENV{LDFLAGS} is no route either: the NDK toolchain's own
# _INIT set wins over it, verified.)

EXPORT_DIR="$PWD/$OUT/export"
APK="$EXPORT_DIR/$PROJECT_NAME.apk"
rm -rf "$EXPORT_DIR"
mkdir -p "$EXPORT_DIR"
if ! godot_export_step 3600 "$OUT/export.log" "$APK" \
    "$FORK_EDITOR" --headless \
    --path "$PWD/$PROJ" --export-debug dn2cpp-android "$APK"; then
    echo "FAIL: --export-debug failed (see below)" >&2
    cat "$OUT/export.log" >&2
    exit 1
fi
# The export exit code is untrustworthy (an export plugin's error downgrades to
# "completed with warnings") — the assertions below are the oracle.
if grep -q "ERROR: Export .NET Project" "$OUT/export.log"; then
    echo "FAIL: the C# export plugin reported an error (see below)" >&2
    cat "$OUT/export.log" >&2
    exit 1
fi
for marker in "dn2cpp: extra transpile args (project setting): --pinvoke-module cri_atom" \
              "dn2cpp: transpiling" "dn2cpp: compiling the drop-in library" "dn2cpp: staged"; do
    grep -qF "$marker" "$OUT/export.log" \
        || { echo "FAIL: marker \"$marker\" missing from the export log" >&2
             cat "$OUT/export.log" >&2; exit 1; }
done
[ -f "$APK" ] || { echo "FAIL: the export produced no APK at $APK" >&2; ls "$EXPORT_DIR" >&2; exit 1; }

# The RID publish (android-arm64) must have selected the package's ANDROID
# managed flavor by itself — the RID machinery fires here, unlike the host-RID
# desktop/web lanes. Byte-compare the published DLL against the package's.
# The publish output lands under the Godot.NET.Sdk's per-RID bin directory.
PUBLISHED_CRI="$PROJ/.godot/mono/temp/bin/ExportDebug/android-arm64/CriWare.CriAtomLE.dll"
[ -f "$PUBLISHED_CRI" ] \
    || { echo "FAIL: no published CriWare.CriAtomLE.dll at $PUBLISHED_CRI" >&2; exit 1; }
cmp -s "$PUBLISHED_CRI" "$CRI_MANAGED_ANDROID" \
    || { echo "FAIL: the publish did not select the android-flavor CriWare.CriAtomLE.dll" >&2
         echo "      published: $PUBLISHED_CRI" >&2; exit 1; }
echo "publish flavor OK: android CriWare.CriAtomLE.dll"

# Listing snapshotted once, then grepped (the SIGPIPE-under-pipefail rule).
LIST="$OUT/apk-contents.txt"
unzip -l "$APK" > "$LIST"
for so in "lib$PROJECT_NAME.so" libcri_atom.so libcri_jni_shared.so libcri_ware_android_le.so; do
    grep -qF "lib/arm64-v8a/$so" "$LIST" \
        || { echo "FAIL: the APK does not carry lib/arm64-v8a/$so" >&2
             grep -i '\.so' "$LIST" >&2; exit 1; }
done
# The pck directory GDMono checks for BEFORE the drop-in fallback.
grep -qE "assets/\.godot/mono/publish/arm64/" "$LIST" \
    || { echo "FAIL: the pck has no .godot/mono/publish/arm64/ — GDMono aborts before the fallback" >&2
         exit 1; }
# The game data must be in the pck: the include_filter carries the ACF/ACB/AWB.
for data in DemoProj.acf DemoProj.acb DemoProj.awb; do
    grep -qF "$data" "$LIST" \
        || { echo "FAIL: the pck does not carry $data" >&2; exit 1; }
done
# No .NET runtime may ship (GDMono only reaches the drop-in fallback when it
# finds neither hostfxr nor coreclr).
stray="$(grep -iE '\.dll|hostfxr|coreclr|libmonosgen|System\..*\.so' "$LIST" || true)"
if [ -n "$stray" ]; then
    echo "FAIL: the APK contains .NET runtime remnants:" >&2
    printf '%s\n' "$stray" >&2
    exit 1
fi
echo "APK OK: drop-in + 3 CRI libraries in lib/arm64-v8a/, data in pck, no .NET runtime"

# ── The device tail: install, run, assert logcat markers ──────────────────────
# The one part no build artifact can stand in for: CRI's audio engine actually
# initializing and rendering on real Android. Needs an attached adb device; its
# absence is a PARTIAL (everything above ran and asserted).
android_ensure_adb || true
SERIAL="${DN2CPP_ANDROID_SERIAL:-$(android_first_device)}"
if [ -z "$SERIAL" ]; then
    gate_partial "no adb device attached — the on-device run was skipped"
    # The concurrent-restage tripwire is NOT part of the device tail and must not
    # ride out with it: stage_editor_toolchain has already run and the export has
    # consumed the shared $FORK_GODOTSHARP/Dn2Cpp tree, so it is live and
    # load-bearing by this point. Dropping it here shrank a section the partial's
    # reason does not even mention; both editor-export siblings call it
    # unconditionally before gate_cache_commit.
    assert_editor_toolchain_current "$FORK_GODOTSHARP"
    gate_cache_commit
    echo "OK"
    exit 0
fi

echo "== 6/6 Running on device $SERIAL =="
PKG=com.criware.godotsampleapp
DEVLOG="$OUT/device-logcat.txt"

# Uninstall-on-every-exit-path: a device must not accumulate gate installs,
# and the keep-screen-on override below must never outlive the run.
device_fail() {
    echo "FAIL: $1" >&2
    [ -f "$DEVLOG" ] && tail -40 "$DEVLOG" >&2
    adb -s "$SERIAL" shell svc power stayon false >/dev/null 2>&1 || true
    adb -s "$SERIAL" shell am force-stop "$PKG" >/dev/null 2>&1 || true
    adb -s "$SERIAL" uninstall "$PKG" >/dev/null 2>&1 || true
    exit 1
}

adb -s "$SERIAL" install -r "$APK" >"$OUT/install.log" 2>&1 \
    || { cat "$OUT/install.log" >&2; device_fail "adb install failed"; }
adb -s "$SERIAL" logcat -c >/dev/null 2>&1 || true

# A sleeping/locked device never resumes the activity, so no frame ever runs
# and no marker ever prints (observed: the task opened with isSleeping=true and
# sat paused — and a device that re-dozed mid-boot paused the game between the
# engine banner and the drop-in init). Keep the screen on for the whole run
# (restored in every exit path), then wake and dismiss with settle pauses —
# best effort, an unsecured lockscreen dismisses.
adb -s "$SERIAL" shell svc power stayon true >/dev/null 2>&1 || true
device_wake() {
    adb -s "$SERIAL" shell input keyevent KEYCODE_WAKEUP >/dev/null 2>&1 || true
    sleep 1
    adb -s "$SERIAL" shell wm dismiss-keyguard >/dev/null 2>&1 || true
    sleep 1
}
device_wake
# The exported LAUNCHER is the activity-alias (GodotApp itself is not
# exported on the stock template — starting it from the shell is a
# SecurityException).
adb -s "$SERIAL" shell am start -n "$PKG/com.godot.game.GodotAppLauncher" >/dev/null 2>&1 \
    || device_fail "am start failed"

# The AutoVerify sequence quits itself after ~3 s of playback polling; poll
# logcat for its terminal marker, bounded well past that. If the game's BOOT
# marker has not appeared after ~20 s, the activity most likely never resumed
# (a re-locked screen) — wake and relaunch once before giving up.
found_done=""
relaunched=""
for _i in $(seq 1 60); do
    adb -s "$SERIAL" logcat -d > "$DEVLOG" 2>/dev/null || true
    if grep -q "CRI_E2E_DONE" "$DEVLOG"; then found_done=1; break; fi
    if [ "$_i" -eq 10 ] && [ -z "$relaunched" ] && ! grep -q "CRI_E2E_BOOT" "$DEVLOG"; then
        relaunched=1
        device_wake
        adb -s "$SERIAL" shell am start -n "$PKG/com.godot.game.GodotAppLauncher" >/dev/null 2>&1 || true
    fi
    sleep 2
done
[ -n "$found_done" ] || device_fail "timed out waiting for CRI_E2E_DONE in logcat"

# Positive markers: engine boot, the drop-in's C# alive (BOOT can only come
# from the transpiled game), CRI initialized (a real version string), the cue
# reaching Playing — the stand-in for audibility: a Playing voice means the
# output stream is being rendered into — and the summary line with the
# playing=True / errors=False verdict baked in.
for marker in \
    "Godot Engine v" \
    "CRI_E2E_BOOT" \
    "CRI_E2E_VERSION CRI Atom" \
    "CRI_E2E_PLAY_STARTED" \
    "CRI_E2E_PLAYING" \
    "CRI_E2E_RESULT playing=True" \
    "CRI_E2E_DONE"; do
    grep -qF "$marker" "$DEVLOG" || device_fail "missing logcat marker: $marker"
done
grep -q "errors=False" <<<"$(grep -F "CRI_E2E_RESULT" "$DEVLOG" || true)" \
    || device_fail "the CRI error callback fired during the run (CRI_E2E_RESULT errors!=False)"
# Negative markers: no CRI error callback, no managed exception, no mono-module
# init failure, no native crash in the game process.
for bad in "CRI_E2E_ERROR" "CRI_E2E_EXCEPTION" \
    "Unable to find the .NET assemblies directory" \
    "GodotPlugins initialization failed"; do
    grep -qF "$bad" "$DEVLOG" && device_fail "logcat contains \"$bad\""
done
if grep -qi "godot\|criware" <<<"$(grep -E "Fatal signal|FATAL EXCEPTION" "$DEVLOG" || true)"; then
    device_fail "the game process crashed (Fatal signal / FATAL EXCEPTION in logcat)"
fi

# Observations for the record (not asserts): the audio stack lines the OS
# printed for the run, and anything JNI-flavored the CRI JNI shim logged —
# libcri_jni_shared.so gets no JNI_OnLoad from a dlopen'd chain, and whether
# that matters is exactly what this run observes.
echo "-- audio stack lines:"
grep -E "AAudio|AudioTrack|OpenSL|audio_hw" "$DEVLOG" | tail -8 || true
echo "-- CRI/JNI lines:"
grep -iE "criware|cri_|JNI_OnLoad" "$DEVLOG" | grep -v "CRI_E2E_" | tail -8 || true

adb -s "$SERIAL" shell svc power stayon false >/dev/null 2>&1 || true
adb -s "$SERIAL" shell am force-stop "$PKG" >/dev/null 2>&1 || true
adb -s "$SERIAL" uninstall "$PKG" >/dev/null 2>&1 \
    || echo "warning: adb uninstall $PKG failed (already removed?)"
echo "device run OK: booted, CRI initialized, cue reached Playing, no errors"

assert_editor_toolchain_current "$FORK_GODOTSHARP"
gate_cache_commit
echo "OK"
