using System.Text;

namespace Dn2Cpp.Godot;

/// <summary>Generates the C# engine shims (<c>GodotShims.g.cs</c>) from
/// <c>extension_api.json</c> so user code can compile against engine types and
/// members. The transpiler's call map is built at runtime from the same JSON by
/// <see cref="GodotCallIntrinsics"/>, so no generated C# is fed back into the
/// transpiler itself.</summary>
public static class BindingGenerator
{
    public static void Run(string jsonPath, string outputShimsPath)
    {
        var (objectClasses, all, utilities, builtins, allBuiltins, globalEnums) = GodotApi.Load(jsonPath);

        var shims = new StringBuilder();
        shims.AppendLine("// <auto-generated />");
        shims.AppendLine("using System;");
        shims.AppendLine();
        shims.AppendLine("namespace Godot");
        shims.AppendLine("{");

        // Global enums (`global_enums`), as top-level enums in the Godot namespace.
        // The builtin-class-owned entries (dotted names: Variant.Type,
        // Variant.Operator) are skipped — their owners have no generated class to
        // nest in — as are enums whose values exceed int32 range (the transpiler
        // models every enum as an int32 stack value; see GodotApi.IsInt32Enum).
        foreach (var e in globalEnums)
        {
            if (e.Name.Contains('.') || !GodotApi.IsInt32Enum(e)) continue;
            EmitEnum(shims, e, e.Name, "    ");
        }

        // Builtin value types (Vector3, …) generated from `builtin_classes`. Emitted
        // as `partial struct` so hand-written method bodies can be added later.
        foreach (var bc in builtins)
        {
            EmitBuiltinClass(shims, bc, allBuiltins);
        }

        // Godot exposes the named colors via a `Colors` class; mirror it.
        if (GodotApi.GeneratedBuiltins.Contains("Color"))
        {
            EmitColorsClass(shims, allBuiltins);
        }

        foreach (var cls in objectClasses)
        {
            // A singleton's ClassDB class is generated as `<Name>Instance`; the engine
            // name goes to the static facade below (GodotApi.InstanceCSharpName). The
            // base clause maps through the same seam, so a class deriving from a
            // singleton (PhysicsServer2DExtension : PhysicsServer2D) still names a
            // type that exists.
            string clsName = GodotApi.InstanceCSharpName(cls);
            string inheritsClause = string.IsNullOrEmpty(cls.Inherits) ? ""
                : $" : {(all.TryGetValue(cls.Inherits, out var baseCls) ? GodotApi.InstanceCSharpName(baseCls) : cls.Inherits)}";
            shims.AppendLine($"    public partial class {clsName}{inheritsClause}");
            shims.AppendLine("    {");

            if (cls.Name == "Object")
            {
                shims.AppendLine("        private System.IntPtr _handle;");
                shims.AppendLine();
                shims.AppendLine("        public Object() {}");
                shims.AppendLine();
            }

            // Per-class enums, nested in the generated partial class. The name is
            // suffixed with `Enum` on collision with a member of the class (e.g.
            // Node's ProcessMode property → ProcessModeEnum), mirroring GodotSharp.
            // A singleton's enums are emitted on its facade instead — GodotSharp
            // spells them `Input.MouseModeEnum`, which is the name an
            // `enum::Input.MouseMode` signature already resolves to.
            if (!cls.IsSingleton)
            {
                foreach (var e in cls.Enums ?? new List<GodotApi.EnumApi>())
                {
                    if (!GodotApi.IsInt32Enum(e)) continue;
                    EmitEnum(shims, e, GodotApi.ClassEnumName(cls, e.Name), "        ");
                }
            }

            EmitClassMethods(shims, cls, all, globalEnums, isStatic: false);
            EmitClassProperties(shims, cls, all, globalEnums, isStatic: false);

            shims.AppendLine("    }");
            shims.AppendLine();

            if (cls.IsSingleton)
            {
                EmitSingletonFacade(shims, cls, all, globalEnums);
            }
        }

        // Global-scope utility functions, routed to the classes the official
        // GodotSharp API places them on: `Mathf` for the math category, `GD`
        // for the general + random ones (which includes the print family).
        EmitUtilityClass(shims, "GD", utilities.Where(u => u.Category is "general" or "random"), all);
        EmitUtilityClass(shims, "Mathf", utilities.Where(u => u.Category == "math"), all);

        shims.AppendLine("}");

        WriteIfChanged(outputShimsPath, shims.ToString());
    }

    /// <summary>Emits the static facade of an engine singleton — the surface game code
    /// writes (<c>ProjectSettings.GlobalizePath(path)</c>) and the one the real
    /// GodotSharp presents, so a game's source builds unchanged on both the GDExtension
    /// and the mono-module lane. It carries the class's enums (named after the engine
    /// owner, which is what an <c>enum::Input.MouseMode</c> signature resolves to), a
    /// <c>Singleton</c> property handing back the engine object, and one static
    /// forwarder per method/property.
    ///
    /// <para>Every member's body is a placeholder, like the rest of the shim surface:
    /// the transpiler intercepts the call and ptrcalls the bind with the engine's
    /// singleton object as the receiver (see GodotCallIntrinsics). The forwarders come
    /// from the same emitters as the instance class's members, so the two surfaces
    /// cannot filter or name a method differently.</para></summary>
    private static void EmitSingletonFacade(StringBuilder shims, GodotApi.ClassApi cls,
        Dictionary<string, GodotApi.ClassApi> all, List<GodotApi.EnumApi> globalEnums)
    {
        shims.AppendLine($"    public static partial class {cls.Name}");
        shims.AppendLine("    {");

        foreach (var e in cls.Enums ?? new List<GodotApi.EnumApi>())
        {
            if (!GodotApi.IsInt32Enum(e)) continue;
            EmitEnum(shims, e, GodotApi.ClassEnumName(cls, e.Name), "        ");
        }

        // The engine's own singleton object, wrapped in a borrowed shim (no
        // singleton is RefCounted, so the wrapper owns nothing and finalizes
        // nothing). Null when this build has no such singleton — an editor-only one
        // in an exported game, JavaScriptBridge off-web — which is a documented
        // degrade, not a crash.
        shims.AppendLine($"        public static {GodotApi.InstanceCSharpName(cls)} Singleton {{ get {{ return default; }} }}");
        shims.AppendLine();

        EmitClassMethods(shims, cls, all, globalEnums, isStatic: true);
        EmitClassProperties(shims, cls, all, globalEnums, isStatic: true);

        shims.AppendLine("    }");
        shims.AppendLine();
    }

    /// <summary>Emits an engine class's method surface. <paramref name="isStatic"/>
    /// selects which of the two surfaces a singleton presents: the instance class
    /// (false — the ordinary receiver-taking members) or the static facade (true —
    /// the same members with the engine's singleton object as their implicit
    /// receiver). Both surfaces come through this one emitter on purpose: they must
    /// filter identically and name identically, and a drift between them is a wrong
    /// method bind, not a compile error.</summary>
    private static void EmitClassMethods(StringBuilder shims, GodotApi.ClassApi cls,
        Dictionary<string, GodotApi.ClassApi> all, List<GodotApi.EnumApi> globalEnums, bool isStatic)
    {
        if (cls.Methods is null) return;

        foreach (var method in cls.Methods)
        {
            if (GodotApi.ExcludedMethods.Contains((cls.Name, method.Name))) continue;
            // A virtual is an engine callback the engine dispatches INTO, never a
            // call target — it has no meaning on a static facade. (The 4.7 dump has
            // none on a singleton class; this keeps the facade sound if one appears.)
            if (isStatic && method.IsVirtual) continue;

            bool allArgsOk = method.Arguments?.All(a => GodotApi.IsSupportedArgType(a.Type, all, globalEnums)) ?? true;
            string? retTypeStr = method.ReturnValue is not null ? GodotApi.MapTypeToCSharp(method.ReturnValue.Type, all, globalEnums) : "void";
            if (retTypeStr is null || !allArgsOk) continue;

            var argsList = new List<string>();
            if (method.Arguments != null)
            {
                // Optional-argument defaults from the dump's `default_value`,
                // emitted for the trailing run of representable ones (C#
                // optional parameters must be trailing) so standard calls
                // like `Connect(signal, callable)` compile.
                var defaults = new string?[method.Arguments.Count];
                for (int ai = 0; ai < method.Arguments.Count; ai++)
                    defaults[ai] = DefaultValueExpr(method.Arguments[ai], all, globalEnums);
                int firstDefault = method.Arguments.Count;
                while (firstDefault > 0 && defaults[firstDefault - 1] is not null)
                    firstDefault--;

                for (int ai = 0; ai < method.Arguments.Count; ai++)
                {
                    var arg = method.Arguments[ai];
                    string csharpType = GodotApi.MapTypeToCSharp(arg.Type, all, globalEnums)!;
                    string argName = GodotApi.ToCamelCase(arg.Name);
                    string def = ai >= firstDefault ? $" = {defaults[ai]}" : "";
                    argsList.Add($"{csharpType} {argName}{def}");
                }
            }

            // A vararg engine method takes extra Variant arguments after its
            // fixed ones; expose the tail as `params Variant[]`. The call is
            // lowered to the variant-call interface (object_method_bind_call),
            // not a ptrcall — its fixed args and this tail are marshalled as an
            // engine Variant array (see GodotCallIntrinsics.EmitVarargCall).
            if (method.IsVararg)
            {
                argsList.Add("params Variant[] @args");
            }

            // Static engine methods have no receiver (null instance ptrcall);
            // virtuals stay overridable callbacks (placeholder bodies by design).
            string modifiers = isStatic ? "public static"
                : method.IsVirtual ? "public virtual"
                : method.IsStatic ? "public static"
                : "public";
            string body = retTypeStr == "void" ? "" : " return default;";
            shims.AppendLine($"        {modifiers} {retTypeStr} {GodotApi.ToPascalCase(method.Name)}({string.Join(", ", argsList)}) {{{body} }}");
        }
    }

    /// <summary>Emits an engine class's property surface, over the accessors
    /// <see cref="EmitClassMethods"/> emitted. <paramref name="isStatic"/> selects
    /// the instance class or the singleton's static facade, exactly as there.</summary>
    private static void EmitClassProperties(StringBuilder shims, GodotApi.ClassApi cls,
        Dictionary<string, GodotApi.ClassApi> all, List<GodotApi.EnumApi> globalEnums, bool isStatic)
    {
        if (cls.Properties is null) return;

        foreach (var prop in cls.Properties)
        {
            var getterMethod = cls.Methods?.FirstOrDefault(m => m.Name == prop.Getter);
            var setterMethod = string.IsNullOrEmpty(prop.Setter) ? null : cls.Methods?.FirstOrDefault(m => m.Name == prop.Setter);

            string? propType = GodotApi.MapTypeToCSharp(prop.Type, all, globalEnums);
            // An enum-typed property is dumped with type `int` while its
            // accessors carry the real enum type; surface the property as
            // the enum so the getter/setter types line up.
            if (prop.Type == "int" && getterMethod?.ReturnValue is not null
                && GodotApi.TryResolveEnum(getterMethod.ReturnValue.Type, all, globalEnums, out _, out var propEnum))
            {
                propType = propEnum;
            }
            if (propType is null) continue;

            bool getterOk = getterMethod is not null &&
                             !GodotApi.ExcludedMethods.Contains((cls.Name, prop.Getter)) &&
                             (getterMethod.Arguments is null || getterMethod.Arguments.Count == 0) &&
                             (getterMethod.ReturnValue is not null && GodotApi.IsSupportedRetType(getterMethod.ReturnValue.Type, all, globalEnums)) &&
                             GodotApi.MapTypeToCSharp(getterMethod.ReturnValue.Type, all, globalEnums) == propType;

            if (!getterOk) continue;

            bool setterOk = setterMethod is not null &&
                             !GodotApi.ExcludedMethods.Contains((cls.Name, prop.Setter)) &&
                             (setterMethod.Arguments is not null && setterMethod.Arguments.Count == 1 && GodotApi.IsSupportedArgType(setterMethod.Arguments[0].Type, all, globalEnums)) &&
                             GodotApi.MapTypeToCSharp(setterMethod.Arguments[0].Type, all, globalEnums) == propType &&
                             (setterMethod.ReturnValue is null || GodotApi.MapTypeToCSharp(setterMethod.ReturnValue.Type, all, globalEnums) is not null);

            string mods = isStatic ? "public static" : "public";
            shims.AppendLine($"        {mods} {propType} {GodotApi.ToPascalCase(prop.Name)}");
            shims.AppendLine("        {");
            shims.AppendLine($"            get => {GodotApi.ToPascalCase(prop.Getter)}();");
            if (setterOk && !string.IsNullOrEmpty(prop.Setter))
            {
                shims.AppendLine($"            set => {GodotApi.ToPascalCase(prop.Setter)}(value);");
            }
            shims.AppendLine("        }");
        }
    }

    /// <summary>The C# default-parameter expression for an engine argument's
    /// <c>default_value</c>, or null when it has none or it isn't representable
    /// as a C# constant expression. Scalars, enums (a cast constant), the string
    /// family, <c>null</c> Objects and <c>null</c> Variants map directly; the
    /// empty Callable/Signal/RID and all-zero builtin struct literals map to
    /// <c>default</c>; empty containers/packed arrays map to <c>null</c> (the
    /// call boundary marshals a null wrapper/array as a fresh empty engine
    /// value — GodotSharp's null→empty convention). Anything else — chiefly
    /// non-zero struct literals like <c>Color(1, 1, 1, 1)</c>, which C# cannot
    /// express as a parameter default — yields null, and the parameter keeps no
    /// default.</summary>
    private static string? DefaultValueExpr(GodotApi.ArgumentApi arg,
        Dictionary<string, GodotApi.ClassApi> all, List<GodotApi.EnumApi> globalEnums)
    {
        string? dv = arg.DefaultValue;
        if (dv is null) return null;
        string type = arg.Type;

        // `null` is the dump default for Object-derived classes and Variant.
        if (dv == "null")
            return type == "Variant" ? "default" : "null";
        if (type == "bool")
            return dv is "true" or "false" ? dv : null;
        if (type == "int")
            return IsNumericLiteral(dv) && !dv.Contains('.') ? dv : null; // C# long param
        if (type == "float")
            return IsNumericLiteral(dv) ? dv : null; // C# double param
        if (type == "String")
            return IsSimpleQuoted(dv) ? dv : null;
        if (type == "StringName")
            return dv.StartsWith("&\"", StringComparison.Ordinal) && IsSimpleQuoted(dv.Substring(1))
                ? dv.Substring(1)
                : null;
        if (type == "NodePath")
        {
            const string prefix = "NodePath(";
            if (dv.StartsWith(prefix, StringComparison.Ordinal) && dv.EndsWith(")", StringComparison.Ordinal))
            {
                string inner = dv.Substring(prefix.Length, dv.Length - prefix.Length - 1);
                if (IsSimpleQuoted(inner)) return inner;
            }
            return null;
        }
        if (GodotApi.TryResolveEnum(type, all, globalEnums, out _, out var enumCs))
            return IsNumericLiteral(dv) && !dv.Contains('.') ? $"({enumCs}){dv}" : null;
        // The empty engine value types whose shim structs default to the same.
        if (type is "Callable" or "Signal" or "RID")
            return dv == type + "()" ? "default" : null;
        if (GodotApi.GeneratedBuiltins.Contains(type))
            return IsAllZeroStructLiteral(dv, type) ? "default" : null;
        if (type == "Array")
            return dv == "[]" ? "null" : null;
        if (type == "Dictionary")
            return dv == "{}" ? "null" : null;
        if (GodotApi.TypedArrayElement(type) is not null)
            return dv.EndsWith("([])", StringComparison.Ordinal) ? "null" : null;
        if (GodotApi.PackedArrayTypes.ContainsKey(type))
            return dv == type + "()" ? "null" : null;
        return null;
    }

    /// <summary>True for a quoted literal safe to emit verbatim as a C# string
    /// (no interior quote or escape to re-interpret).</summary>
    private static bool IsSimpleQuoted(string s)
    {
        if (s.Length < 2 || s[0] != '"' || s[^1] != '"') return false;
        string inner = s.Substring(1, s.Length - 2);
        return !inner.Contains('"') && !inner.Contains('\\');
    }

    /// <summary>True when <paramref name="dv"/> is <c>Type(0, 0, …)</c> with every
    /// component zero — the one struct literal C# can express as a parameter
    /// default (<c>default</c>).</summary>
    private static bool IsAllZeroStructLiteral(string dv, string type)
    {
        if (!dv.StartsWith(type + "(", StringComparison.Ordinal) || !dv.EndsWith(")", StringComparison.Ordinal))
            return false;
        string inner = dv.Substring(type.Length + 1, dv.Length - type.Length - 2);
        foreach (var part in inner.Split(','))
        {
            string p = part.Trim();
            if (!IsNumericLiteral(p)) return false;
            if (!double.TryParse(p, System.Globalization.NumberStyles.Float,
                    System.Globalization.CultureInfo.InvariantCulture, out double val) || val != 0)
                return false;
        }
        return true;
    }

    /// <summary>Emits one enum declaration (global or class-nested). All generated
    /// enums use the default <c>int</c> backing — anything wider is filtered out
    /// before this is called (<see cref="GodotApi.IsInt32Enum"/>). Bitfields get a
    /// <c>[Flags]</c> attribute (metadata only — the transpiler sees plain int32
    /// values either way, so it costs nothing and keeps ToString/composition
    /// semantics honest for managed runs).</summary>
    private static void EmitEnum(StringBuilder shims, GodotApi.EnumApi e, string csharpName, string indent)
    {
        if (e.IsBitfield)
            shims.AppendLine($"{indent}[Flags]");
        shims.AppendLine($"{indent}public enum {csharpName}");
        shims.AppendLine($"{indent}{{");
        foreach (var v in e.Values ?? new List<GodotApi.EnumValueApi>())
        {
            shims.AppendLine($"{indent}    {GodotApi.EnumValueName(csharpName, e.Name, v.Name)} = {v.Value},");
        }
        shims.AppendLine($"{indent}}}");
        shims.AppendLine();
    }

    /// <summary>Emits a builtin value type (e.g. <c>Vector3</c>) from its
    /// <c>builtin_classes</c> entry: real-storage fields from <c>members</c>,
    /// synthesizable constructors (field-init / copy), component-wise
    /// arithmetic/equality operators (only when every field is a primitive scalar),
    /// and constants. Instance <b>methods</b> are not emitted — the JSON carries no
    /// body, so emitting a placeholder would silently produce wrong results (the
    /// "loud, never silent" rule); the type is a <c>partial</c> struct so the common
    /// math can be hand-written (see <c>Vector2.cs</c>/<c>Vector3.cs</c>).</summary>
    private static void EmitBuiltinClass(StringBuilder shims, GodotApi.BuiltinClassApi bc,
        Dictionary<string, GodotApi.BuiltinClassApi> allBuiltins)
    {
        var members = bc.Members ?? new List<GodotApi.MemberApi>();
        // Restrict to the real-storage members (in their canonical order) for types
        // whose `members` list mixes in derived values (e.g. Color).
        if (GodotApi.BuiltinRealMembers.TryGetValue(bc.Name, out var realNames))
        {
            members = realNames
                .Select(n => members.FirstOrDefault(m => m.Name == n))
                .Where(m => m != null)
                .Select(m => m!)
                .ToList();
        }
        if (members.Count == 0) return;

        // Every member must be a primitive we can store as a real field; otherwise
        // the layout would be wrong (a nested builtin / derived member) — skip the type.
        var fields = new List<(string CSharpType, string FieldName, string MemberName)>();
        foreach (var m in members)
        {
            string? ft = GodotApi.MapMemberTypeToCSharp(m.Type);
            if (ft == null) return;
            fields.Add((ft, GodotApi.ToPascalCase(m.Name), m.Name));
        }

        shims.AppendLine($"    public partial struct {bc.Name}");
        shims.AppendLine("    {");

        foreach (var (csharpType, fieldName, _) in fields)
        {
            shims.AppendLine($"        public {csharpType} {fieldName};");
        }
        shims.AppendLine();

        EmitBuiltinConstructors(shims, bc, fields);
        // Component-wise operators/equality only make sense when every field is a
        // primitive scalar; skip them for types with nested value-type fields
        // (e.g. Rect2's Vector2 fields — its only ops are cross-type anyway).
        if (fields.All(f => f.CSharpType is "float" or "int" or "bool"))
        {
            EmitBuiltinOperators(shims, bc, fields);
        }
        EmitBuiltinConstants(shims, bc, fields, allBuiltins);
        EmitBuiltinBridgeMethods(shims, bc);

        shims.AppendLine("    }");
        shims.AppendLine();
    }

    /// <summary>Emits placeholder-body signatures for the curated builtin instance
    /// methods exposed via the engine bridge (<see cref="GodotApi.BridgedBuiltinMethods"/>).
    /// The body is never executed — <c>GodotCallIntrinsics</c> lowers the call to a
    /// runtime <c>variant_get_ptr_builtin_method</c> invocation — but it lets user code
    /// compile against the method.
    ///
    /// <para>The gates mirror the call-map side (<c>GodotCallIntrinsics.BuildBuiltinMethods</c>),
    /// INCLUDING the receiver-tag gate: a curated tuple whose receiver has no bridge tag
    /// would otherwise emit a placeholder body the map never lowers — user code compiles
    /// against it and silently gets <c>default</c> at run time. A curated tuple failing
    /// any gate is therefore a hard error, not a silent skip.</para></summary>
    private static void EmitBuiltinBridgeMethods(StringBuilder shims, GodotApi.BuiltinClassApi bc)
    {
        foreach (var m in bc.Methods ?? new List<GodotApi.MethodApi>())
        {
            if (!GodotApi.BridgedBuiltinMethods.Contains((bc.Name, m.Name)))
                continue;
            if (m.IsStatic)
                throw new NotSupportedException(
                    $"BridgedBuiltinMethods: {bc.Name}.{m.Name} is static — not a bridgeable instance method");
            if (GodotApi.BridgeGdTag(bc.Name) is null)
                throw new NotSupportedException(
                    $"BridgedBuiltinMethods: receiver type {bc.Name} has no bridge tag ({bc.Name}.{m.Name})");

            string? retCs = m.ReturnType == null ? "void" : GodotApi.MapMemberTypeToCSharp(m.ReturnType);
            if (retCs == null || GodotApi.BridgeGdTag(m.ReturnType) == null)
                throw new NotSupportedException(
                    $"BridgedBuiltinMethods: return type {m.ReturnType} has no bridge shape ({bc.Name}.{m.Name})");

            var argParts = new List<string>();
            foreach (var a in m.Arguments ?? new List<GodotApi.ArgumentApi>())
            {
                string? at = GodotApi.MapMemberTypeToCSharp(a.Type);
                if (at == null || GodotApi.BridgeGdTag(a.Type) is null or 0)
                    throw new NotSupportedException(
                        $"BridgedBuiltinMethods: argument type {a.Type} has no bridge shape ({bc.Name}.{m.Name})");
                argParts.Add($"{at} {GodotApi.ToCamelCase(a.Name)}");
            }

            string body = retCs == "void" ? "" : " return default;";
            shims.AppendLine($"        public {retCs} {GodotApi.ToPascalCase(m.Name)}({string.Join(", ", argParts)}) {{{body} }}");
        }
        shims.AppendLine();
    }

    /// <summary>Emits the constructors whose body we can synthesize: a field-init
    /// ctor (the argument types match the fields positionally — a value type's full
    /// constructor) or a copy ctor (a single argument of the same type).
    /// Constructors we can't synthesize — the empty ctor (<c>default</c> already
    /// covers it) and cross-type conversions — are skipped.</summary>
    private static void EmitBuiltinConstructors(StringBuilder shims, GodotApi.BuiltinClassApi bc,
        List<(string CSharpType, string FieldName, string MemberName)> fields)
    {
        foreach (var ctor in bc.Constructors ?? new List<GodotApi.ConstructorApi>())
        {
            var args = ctor.Arguments;
            if (args == null || args.Count == 0) continue; // default(T) covers the empty ctor

            // Copy ctor: a single argument of this same type → copy every field.
            if (args.Count == 1 && args[0].Type == bc.Name)
            {
                string src = GodotApi.ToCamelCase(args[0].Name);
                shims.AppendLine($"        public {bc.Name}({bc.Name} {src})");
                shims.AppendLine("        {");
                foreach (var (_, fieldName, _) in fields)
                    shims.AppendLine($"            {fieldName} = {src}.{fieldName};");
                shims.AppendLine("        }");
                shims.AppendLine();
                continue;
            }

            // Field-init ctor: the argument types match the fields positionally
            // (a value type's full constructor). Names are ignored — Godot's matrix
            // types name the args `x_axis`/`y_axis`/… while the members are `x`/`y`/…
            // — and the param names are taken from the members instead.
            if (args.Count != fields.Count) continue;
            bool typeMatch = true;
            for (int i = 0; i < args.Count; i++)
            {
                if (GodotApi.MapMemberTypeToCSharp(args[i].Type) != fields[i].CSharpType)
                {
                    typeMatch = false;
                    break;
                }
            }
            if (!typeMatch) continue;

            var paramList = string.Join(", ", fields.Select(f => $"{f.CSharpType} {GodotApi.ToCamelCase(f.MemberName)}"));
            shims.AppendLine($"        public {bc.Name}({paramList})");
            shims.AppendLine("        {");
            foreach (var f in fields)
                shims.AppendLine($"            {f.FieldName} = {GodotApi.ToCamelCase(f.MemberName)};");
            shims.AppendLine("        }");
            shims.AppendLine();
        }
    }

    /// <summary>Emits the operators whose body can be synthesized component-wise
    /// in pure C# — and only those whose return type is this same type, so the
    /// math is genuinely component-wise (skipping cross-type ops like
    /// <c>Quaternion * Vector3</c> rotation, <c>Vector2i * float → Vector2</c>
    /// and matrix products, which need real engine math):
    /// binary <c>+ - * / %</c> against this type (component op component), the
    /// scalar <c>* / %</c> against <c>int</c>/<c>float</c> (component op scalar),
    /// unary <c>-</c>, and component-wise equality (<c>==</c>/<c>!=</c> plus the
    /// <c>Equals</c>/<c>GetHashCode</c> the compiler requires). The relational
    /// operators (<c>&lt; &lt;= &gt; &gt;=</c>) stay skipped — Godot's are
    /// lexicographic, not component-wise.</summary>
    private static void EmitBuiltinOperators(StringBuilder shims, GodotApi.BuiltinClassApi bc,
        List<(string CSharpType, string FieldName, string MemberName)> fields)
    {
        foreach (var op in bc.Operators ?? new List<GodotApi.OperatorApi>())
        {
            // Equality: synthesize component-wise == / != (and the Equals/GetHashCode
            // the C# compiler requires alongside them) from the self-typed `==`.
            // The Variant-typed == / != entries and the standalone != are skipped —
            // they're covered here.
            if (op.Name == "==" && op.RightType == bc.Name)
            {
                string eq = string.Join(" && ", fields.Select(f => $"a.{f.FieldName} == b.{f.FieldName}"));
                string hash = string.Join(" ^ ", fields.Select(f => $"{f.FieldName}.GetHashCode()"));
                shims.AppendLine($"        public static bool operator ==({bc.Name} a, {bc.Name} b) => {eq};");
                shims.AppendLine($"        public static bool operator !=({bc.Name} a, {bc.Name} b) => !(a == b);");
                shims.AppendLine($"        public override bool Equals(object obj) => obj is {bc.Name} o && this == o;");
                shims.AppendLine($"        public override int GetHashCode() => {hash};");
                continue;
            }

            // Only ops that produce this same type are safely component-wise.
            if (op.ReturnType != bc.Name) continue;

            if (op.Name == "unary-")
            {
                string body = string.Join(", ", fields.Select(f => $"-a.{f.FieldName}"));
                shims.AppendLine($"        public static {bc.Name} operator -({bc.Name} a) => new {bc.Name}({body});");
                continue;
            }

            // Binary arithmetic only.
            if (op.Name is not ("+" or "-" or "*" or "/" or "%")) continue;
            if (string.IsNullOrEmpty(op.RightType)) continue;

            if (op.RightType == bc.Name)
            {
                // Quaternion * Quaternion is the Hamilton product, NOT component-wise
                // (component-wise would compile but silently return garbage), so it is
                // hand-written in the Quaternion partial. Component-wise +/- are still
                // correct for quaternions and stay synthesized here.
                if (op.Name == "*" && bc.Name == "Quaternion") continue;

                // Component op component (genuinely component-wise for the vector types,
                // whose same-type * is the Hadamard product).
                string body = string.Join(", ", fields.Select(f => $"a.{f.FieldName} {op.Name} b.{f.FieldName}"));
                shims.AppendLine($"        public static {bc.Name} operator {op.Name}({bc.Name} a, {bc.Name} b) => new {bc.Name}({body});");
            }
            else if (op.Name is "*" or "/" or "%" && op.RightType is "int" or "float")
            {
                // Component op scalar (Godot defines scalar only for * / %).
                string scalarType = GodotApi.MapMemberTypeToCSharp(op.RightType)!;
                string body = string.Join(", ", fields.Select(f => $"a.{f.FieldName} {op.Name} s"));
                shims.AppendLine($"        public static {bc.Name} operator {op.Name}({bc.Name} a, {scalarType} s) => new {bc.Name}({body});");
            }
        }
        shims.AppendLine();
    }

    /// <summary>Emits the constants whose literal is plain numbers (e.g.
    /// <c>Vector3(0, 0, 0)</c>) as static properties. Constants with non-numeric
    /// args (<c>inf</c>/<c>nan</c>/nested expressions) are skipped for now.</summary>
    private static void EmitBuiltinConstants(StringBuilder shims, GodotApi.BuiltinClassApi bc,
        List<(string CSharpType, string FieldName, string MemberName)> fields,
        Dictionary<string, GodotApi.BuiltinClassApi> allBuiltins)
    {
        foreach (var c in bc.Constants ?? new List<GodotApi.ConstantApi>())
        {
            if (c.Type != bc.Name) continue; // only same-type constants

            int open = c.Value.IndexOf('(');
            int close = c.Value.LastIndexOf(')');
            if (open < 0 || close <= open) continue;

            string inner = c.Value.Substring(open + 1, close - open - 1);
            var parts = inner.Split(',').Select(p => p.Trim()).ToList();
            // The dump lists constants as flat scalars (`Transform2D(1, 0, 0, 1, 0,
            // 0)`); build each field's (possibly nested) ctor expression from the
            // right slice. Skip non-numeric values (`inf`/`nan` constants).
            if (parts.Count == 0 || !parts.All(IsNumericLiteral)) continue;

            int pos = 0;
            var exprs = new List<string>();
            bool ok = true;
            foreach (var f in fields)
            {
                string? e = BuildConstantExpr(f.CSharpType, parts, ref pos, allBuiltins);
                if (e == null) { ok = false; break; }
                exprs.Add(e);
            }
            if (!ok || pos != parts.Count) continue; // must consume exactly all scalars

            shims.AppendLine($"        public static {bc.Name} {GodotApi.ConstNameToPascal(c.Name)} => new {bc.Name}({string.Join(", ", exprs)});");
        }
        shims.AppendLine();
    }

    /// <summary>Emits the <c>Colors</c> static class standard Godot C# uses for the
    /// named colors (<c>Colors.Red</c>), aliasing the constants already generated on
    /// <c>Color</c> so both <c>Colors.X</c> and <c>Color.X</c> compile.</summary>
    private static void EmitColorsClass(StringBuilder shims, Dictionary<string, GodotApi.BuiltinClassApi> allBuiltins)
    {
        if (!allBuiltins.TryGetValue("Color", out var color) || color.Constants == null) return;

        shims.AppendLine("    public static class Colors");
        shims.AppendLine("    {");
        foreach (var c in color.Constants)
        {
            if (c.Type != "Color") continue;
            // Only alias constants that were actually emitted on Color (numeric value).
            int open = c.Value.IndexOf('(');
            int close = c.Value.LastIndexOf(')');
            if (open < 0 || close <= open) continue;
            var parts = c.Value.Substring(open + 1, close - open - 1).Split(',').Select(p => p.Trim());
            if (!parts.All(IsNumericLiteral)) continue;

            string name = GodotApi.ConstNameToPascal(c.Name);
            shims.AppendLine($"        public static Color {name} => Color.{name};");
        }
        shims.AppendLine("    }");
        shims.AppendLine();
    }

    /// <summary>Builds the constructor expression for <paramref name="csharpType"/>,
    /// consuming exactly its flattened scalar count of literals from
    /// <paramref name="parts"/> at <paramref name="pos"/> (advanced past them). A
    /// scalar consumes one literal (a <c>float</c> gets the <c>f</c> suffix); a
    /// value type recurses over its real-storage fields (e.g. a <c>Transform2D</c>
    /// constant's six scalars become three <c>new Vector2(...)</c>). Returns null if
    /// the type isn't modeled or the literals run out.</summary>
    private static string? BuildConstantExpr(string csharpType, List<string> parts, ref int pos,
        Dictionary<string, GodotApi.BuiltinClassApi> allBuiltins)
    {
        if (csharpType is "float" or "int" or "bool")
        {
            if (pos >= parts.Count) return null;
            string lit = parts[pos++];
            return csharpType == "float" ? lit + "f" : lit;
        }

        var fieldTypes = RealFieldTypes(csharpType, allBuiltins);
        if (fieldTypes == null) return null;

        var args = new List<string>();
        foreach (var t in fieldTypes)
        {
            string? e = BuildConstantExpr(t, parts, ref pos, allBuiltins);
            if (e == null) return null;
            args.Add(e);
        }
        return $"new {csharpType}({string.Join(", ", args)})";
    }

    /// <summary>The ordered C# types of a value type's real-storage fields (honoring
    /// the <c>BuiltinRealMembers</c> override), or null if it isn't a modeled value
    /// type or has a member we can't map.</summary>
    private static List<string>? RealFieldTypes(string name, Dictionary<string, GodotApi.BuiltinClassApi> allBuiltins)
    {
        if (!allBuiltins.TryGetValue(name, out var bc) || bc.Members == null) return null;

        var members = bc.Members;
        if (GodotApi.BuiltinRealMembers.TryGetValue(name, out var realNames))
        {
            members = realNames.Select(n => members.FirstOrDefault(m => m.Name == n)).Where(m => m != null).Select(m => m!).ToList();
        }

        var types = new List<string>();
        foreach (var m in members)
        {
            string? t = GodotApi.MapMemberTypeToCSharp(m.Type);
            if (t == null) return null;
            types.Add(t);
        }
        return types;
    }

    /// <summary>True when <paramref name="s"/> is a plain decimal literal (optional
    /// sign / fractional part), so it can be emitted verbatim as a C# numeric arg.</summary>
    private static bool IsNumericLiteral(string s)
    {
        if (s.Length == 0) return false;
        int i = (s[0] == '-' || s[0] == '+') ? 1 : 0;
        if (i >= s.Length) return false;
        bool dot = false;
        for (; i < s.Length; i++)
        {
            if (s[i] == '.')
            {
                if (dot) return false;
                dot = true;
            }
            else if (!char.IsDigit(s[i]))
            {
                return false;
            }
        }
        return true;
    }

    /// <summary>Emits a static class of global-scope utility functions (e.g.
    /// <c>GD</c>/<c>Mathf</c>). Bodies are placeholders — calls are lowered by
    /// the transpiler's intrinsics where supported (currently <c>GD.Print</c>);
    /// the rest just let standard code compile. Functions whose return or any
    /// argument type isn't modeled yet (Packed*/RID) are skipped.</summary>
    private static void EmitUtilityClass(StringBuilder shims, string className,
        IEnumerable<GodotApi.UtilityFunctionApi> functions, Dictionary<string, GodotApi.ClassApi> all)
    {
        // `partial` so hand-written members can be added (e.g. Mathf's constants,
        // which aren't in `utility_functions`).
        shims.AppendLine($"    public static partial class {className}");
        shims.AppendLine("    {");

        foreach (var fn in functions)
        {
            string? retType = GodotApi.MapUtilTypeToCSharp(fn.ReturnType, all);
            if (retType == null) continue;

            string paramList;
            if (fn.IsVararg)
            {
                // Godot varargs take Variant arguments (the print family, str, …).
                paramList = "params Variant[] args";
            }
            else
            {
                var parts = new List<string>();
                bool ok = true;
                foreach (var arg in fn.Arguments ?? new List<GodotApi.ArgumentApi>())
                {
                    string? t = GodotApi.MapUtilTypeToCSharp(arg.Type, all);
                    if (t == null || t == "void") { ok = false; break; }
                    parts.Add($"{t} {GodotApi.ToCamelCase(arg.Name)}");
                }
                if (!ok) continue;
                paramList = string.Join(", ", parts);
            }

            string body = retType == "void" ? "" : " return default;";
            shims.AppendLine($"        public static {retType} {GodotApi.ToPascalCase(fn.Name)}({paramList}) {{{body} }}");
        }

        shims.AppendLine("    }");
        shims.AppendLine();
    }

    /// <summary>Writes only when content differs, so unchanged regenerations
    /// don't touch the file's timestamp and trigger needless recompiles.</summary>
    private static void WriteIfChanged(string path, string content)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        if (File.Exists(path) && File.ReadAllText(path) == content)
            return;
        File.WriteAllText(path, content);
    }
}
