cmake_minimum_required(VERSION 3.21)
if(NOT CMAKE_HOST_SYSTEM_NAME MATCHES "^(Darwin|Windows)$")
    message(FATAL_ERROR "Android DeClang requires a macOS or Windows host")
endif()
set(DN2CPP_DECLANG_HOST_SUFFIX "")
if(CMAKE_HOST_WIN32)
    set(DN2CPP_DECLANG_HOST_SUFFIX ".exe")
endif()
foreach(variable DN2CPP_DECLANG_COMPILER ANDROID_NDK CMAKE_ANDROID_NDK)
    string(REPLACE "\\" "/" ${variable} "${${variable}}")
endforeach()
if(NOT ANDROID_NDK)
    set(ANDROID_NDK "${CMAKE_ANDROID_NDK}")
endif()
if(NOT EXISTS "${ANDROID_NDK}/build/cmake/android.toolchain.cmake")
    message(FATAL_ERROR "Android DeClang requires ANDROID_NDK")
endif()
if(NOT EXISTS "${DN2CPP_DECLANG_COMPILER}" OR IS_DIRECTORY "${DN2CPP_DECLANG_COMPILER}")
    message(FATAL_ERROR "DN2CPP_DECLANG_COMPILER must name a DeClang executable")
endif()
if(NOT ANDROID_ABI)
    set(ANDROID_ABI arm64-v8a)
endif()
if(NOT ANDROID_ABI STREQUAL "arm64-v8a")
    message(FATAL_ERROR "Android DeClang supports only arm64-v8a")
endif()
if(NOT ANDROID_PLATFORM)
    set(ANDROID_PLATFORM android-24)
endif()
if(NOT ANDROID_STL)
    set(ANDROID_STL c++_static)
endif()
if(NOT ANDROID_STL MATCHES "^c\\+\\+_(static|shared)$")
    message(FATAL_ERROR "Android DeClang requires c++_static or c++_shared")
endif()
# Identification precedes runtime integration, and OFF builds have no manifest
# launcher. Both must be isolated from the user's ambient DeClang config.
include("${CMAKE_CURRENT_LIST_DIR}/declang_home.cmake")
dn2cpp_declang_home("${CMAKE_BINARY_DIR}/declang/toolchain-disabled" _declang_disabled_home)
file(WRITE "${_declang_disabled_home}/.DeClang/config.json" "{\"enable_obfuscation\":0}\n")
set(ENV{DECLANG_HOME} "${_declang_disabled_home}")
set(DN2CPP_DECLANG_DISABLED_LAUNCHER "${CMAKE_COMMAND};-E;env;DECLANG_HOME=${_declang_disabled_home}")
file(SHA256 "${DN2CPP_DECLANG_COMPILER}" _declang_compiler_hash)
if(DEFINED DN2CPP_DECLANG_COMPILER_HASH AND NOT DN2CPP_DECLANG_COMPILER_HASH STREQUAL _declang_compiler_hash)
    # CMake otherwise reuses compiler identification when an executable is
    # replaced at the same path, even after its build dependencies change.
    foreach(language C CXX)
        file(REMOVE "${CMAKE_PLATFORM_INFO_DIR}/CMake${language}Compiler.cmake")
        unset(CMAKE_${language}_COMPILER_ID_RUN)
        unset(CMAKE_${language}_COMPILER_LOADED)
    endforeach()
endif()
set(DN2CPP_DECLANG_COMPILER_HASH "${_declang_compiler_hash}" CACHE INTERNAL "DeClang executable identity" FORCE)
include("${ANDROID_NDK}/build/cmake/android.toolchain.cmake")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES DN2CPP_DECLANG_COMPILER ANDROID_NDK ANDROID_ABI ANDROID_PLATFORM ANDROID_STL)
# The NDK is included first on every configure; compiler identification and PCH
# must see the same driver as ordinary translation units.
set(CMAKE_C_COMPILER "${DN2CPP_DECLANG_COMPILER}")
set(CMAKE_CXX_COMPILER "${DN2CPP_DECLANG_COMPILER}")
set(CMAKE_C_COMPILER "${DN2CPP_DECLANG_COMPILER}" CACHE FILEPATH "DeClang C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${DN2CPP_DECLANG_COMPILER}" CACHE FILEPATH "DeClang C++ compiler" FORCE)
set(CMAKE_C_COMPILER_ARG1 "--driver-mode=gcc" CACHE STRING "C driver mode" FORCE)
set(CMAKE_CXX_COMPILER_ARG1 "--driver-mode=g++" CACHE STRING "C++ driver mode" FORCE)
set(CMAKE_C_LINKER_LAUNCHER "${CMAKE_COMMAND};-DDRIVER=${ANDROID_TOOLCHAIN_ROOT}/bin/clang${DN2CPP_DECLANG_HOST_SUFFIX};-P;${CMAKE_CURRENT_LIST_DIR}/declang_android_link.cmake;--")
set(CMAKE_CXX_LINKER_LAUNCHER "${CMAKE_COMMAND};-DDRIVER=${ANDROID_TOOLCHAIN_ROOT}/bin/clang++${DN2CPP_DECLANG_HOST_SUFFIX};-P;${CMAKE_CURRENT_LIST_DIR}/declang_android_link.cmake;--")
foreach(language C CXX)
    if(CMAKE_${language}_COMPILER_LAUNCHER AND NOT CMAKE_${language}_COMPILER_LAUNCHER STREQUAL DN2CPP_DECLANG_DISABLED_LAUNCHER)
        message(FATAL_ERROR "Android DeClang does not support compiler caches or custom compiler launchers")
    endif()
    set(CMAKE_${language}_COMPILER_LAUNCHER "${DN2CPP_DECLANG_DISABLED_LAUNCHER}")
endforeach()
