cmake_minimum_required(VERSION 3.21)
# Keep the NDK's sysroot, CRT, compiler-rt, libc++ and linker selection together
# by replacing only the compiler driver in CMake's generated link command.
set(args)
set(after_separator FALSE)
foreach(i RANGE 0 ${CMAKE_ARGC})
    if(after_separator)
        list(APPEND args "${CMAKE_ARGV${i}}")
    elseif(CMAKE_ARGV${i} STREQUAL "--")
        set(after_separator TRUE)
    endif()
endforeach()
if(NOT args OR NOT EXISTS "${DRIVER}")
    message(FATAL_ERROR "Android DeClang linker requires an NDK driver and link command")
endif()
list(REMOVE_AT args 0)
execute_process(COMMAND "${DRIVER}" ${args} RESULT_VARIABLE status)
if(NOT status STREQUAL "0")
    message(FATAL_ERROR "Android NDK link failed: ${status}")
endif()
