cmake_minimum_required(VERSION 3.20)
# A compiler invocation owns its home: DeClang appends to a fixed log filename.
set(args)
set(after_separator FALSE)
math(EXPR last "${CMAKE_ARGC} - 1")
foreach(i RANGE 0 ${last})
    if(after_separator)
        list(APPEND args "${CMAKE_ARGV${i}}")
    elseif(CMAKE_ARGV${i} STREQUAL "--")
        set(after_separator TRUE)
    endif()
endforeach()
if(NOT args)
    message(FATAL_ERROR "DeClang launcher: missing compiler command")
endif()
set(source "")
set(object "")
set(next_object FALSE)
set(next_depfile FALSE)
set(depfile "")
foreach(arg IN LISTS args)
    if(arg MATCHES "^-flto" OR arg MATCHES "^-.*(antihack|obfuscation)|^@" OR arg MATCHES "^(.*[/\\])?(ccache|sccache)$")
        message(FATAL_ERROR "DeClang does not support LTO or compiler caches")
    endif()
    if(next_depfile)
        set(depfile "${arg}")
        set(next_depfile FALSE)
    elseif(arg STREQUAL "-MF")
        set(next_depfile TRUE)
    elseif(next_object)
        set(object "${arg}")
        set(next_object FALSE)
    elseif(arg STREQUAL "-o")
        set(next_object TRUE)
    elseif(arg MATCHES "\\.cpp$")
        get_filename_component(source "${arg}" ABSOLUTE)
    endif()
endforeach()
string(SHA256 key "${object}")
set(home "${WORK_DIR}/invocations/${key}")
set(record_home "${home}")
include("${CMAKE_CURRENT_LIST_DIR}/declang_home.cmake")
dn2cpp_declang_home("${record_home}" home)
file(MAKE_DIRECTORY "${record_home}/.DeClang")
set(result "")
set(selected)
set(flatten "[]")
if(source AND CONFIG AND APP_DIR)
    get_filename_component(source_dir "${source}" DIRECTORY)
    get_filename_component(source_name "${source}" NAME)
    get_filename_component(app_dir "${APP_DIR}" ABSOLUTE)
    if(source_dir STREQUAL app_dir)
        file(READ "${CONFIG}" manifest)
        string(JSON count LENGTH "${manifest}" targets)
        if(count GREATER 0)
            math(EXPR end "${count} - 1")
            foreach(i RANGE 0 ${end})
                string(JSON cpp GET "${manifest}" targets ${i} cppFile)
                if(cpp STREQUAL source_name)
                    string(JSON pattern GET "${manifest}" targets ${i} symbolPattern)
                    if(pattern IN_LIST selected)
                        continue()
                    endif()
                    string(JSON seed GET "${manifest}" targets ${i} seed)
                    if(NOT seed MATCHES "^[0-9a-f]+$")
                        message(FATAL_ERROR "Invalid DeClang seed")
                    endif()
                    string(LENGTH "${seed}" seed_length)
                    if(NOT seed_length EQUAL 32)
                        message(FATAL_ERROR "DeClang seeds must contain 32 hex digits")
                    endif()
                    string(JSON row SET "{}" name "\"${pattern}\"")
                    string(JSON row SET "${row}" split_level 1)
                    string(JSON row SET "${row}" seed "\"${seed}\"")
                    string(JSON size LENGTH "${flatten}")
                    string(JSON flatten SET "${flatten}" ${size} "${row}")
                    list(APPEND selected "${pattern}")
                endif()
            endforeach()
        endif()
        set(result "${WORK_DIR}/results/${source_name}.json")
        file(MAKE_DIRECTORY "${WORK_DIR}/results")
        file(REMOVE "${result}" "${result}.tmp")

    endif()
endif()
if(selected)
    set(config "{\"enable_obfuscation\":1,\"overall_obfuscation\":0,\"split_level\":1,\"flatten\":${flatten}}")
else()
    set(config "{\"enable_obfuscation\":0}")
endif()
file(WRITE "${home}/.DeClang/config.json" "${config}\n")
file(REMOVE "${home}/.DeClang/log.txt")
if(NOT home STREQUAL record_home)
    file(WRITE "${record_home}/.DeClang/config.json" "${config}\n")
    file(REMOVE "${record_home}/.DeClang/log.txt")
endif()
set(ENV{DECLANG_HOME} "${home}")
execute_process(COMMAND ${args} RESULT_VARIABLE status)
if(NOT home STREQUAL record_home AND EXISTS "${home}/.DeClang/log.txt")
    configure_file("${home}/.DeClang/log.txt" "${record_home}/.DeClang/log.txt" COPYONLY)
endif()
if(NOT status STREQUAL "0")
    message(FATAL_ERROR "DeClang compiler failed: ${status}")
endif()
set(successes "[]")
if(selected AND NOT EXISTS "${home}/.DeClang/log.txt")
    message(FATAL_ERROR "DeClang produced no application log: ${source}")
endif()
if(EXISTS "${home}/.DeClang/log.txt")
    file(STRINGS "${home}/.DeClang/log.txt" lines)
    set(applied)
    foreach(line IN LISTS lines)
        if(line MATCHES "Successfully flattened func")
            if(NOT line MATCHES "^\\[Frontend\\]: Successfully flattened func ([_A-Za-z0-9.$]+)$")
                message(FATAL_ERROR "Unrecognized DeClang success record: ${line}")
            endif()
            set(symbol "${CMAKE_MATCH_1}")
            set(matched FALSE)
            foreach(pattern IN LISTS selected)
                if(symbol MATCHES "${pattern}")
                    set(matched TRUE)
                    list(APPEND applied "${pattern}")
                endif()
            endforeach()
            if(NOT matched)
                message(FATAL_ERROR "DeClang applied to an unselected function: ${symbol}")
            endif()
            string(JSON size LENGTH "${successes}")
            string(JSON successes SET "${successes}" ${size} "\"${symbol}\"")
        elseif(line MATCHES "^\\[Frontend\\]: (Flattening func |Splitting )([_A-Za-z0-9.$]+)( by [0-9]+)?$")
            set(symbol "${CMAKE_MATCH_2}")
            set(matched FALSE)
            foreach(pattern IN LISTS selected)
                if(symbol MATCHES "${pattern}")
                    set(matched TRUE)
                endif()
            endforeach()
            if(NOT matched)
                message(FATAL_ERROR "DeClang selected an unrequested function: ${symbol}")
            endif()
        elseif(line MATCHES "^ \"" OR line STREQUAL " (in-process)" OR line STREQUAL "[Frontend]: Doing overallObf: 0%" OR line STREQUAL "[Frontend]: (Info) enable_obf is 0, all obfuscations will be disabled.")
            continue()
        else()
            message(FATAL_ERROR "Unrecognized DeClang log record: ${line}")
        endif()
    endforeach()
    foreach(pattern IN LISTS selected)
        if(NOT pattern IN_LIST applied)
            message(FATAL_ERROR "DeClang did not successfully flatten ${pattern}; see ${home}/.DeClang/log.txt")
        endif()
    endforeach()
endif()
if(result)
    file(WRITE "${result}.tmp" "{\"version\":1,\"cppFile\":\"${source_name}\",\"flattenedSymbols\":${successes}}\n")
    if(NOT depfile OR NOT EXISTS "${depfile}" OR NOT EXISTS "${object}")
        message(FATAL_ERROR "DeClang requires a compiler depfile and object to track application results")
    endif()
    file(RENAME "${result}.tmp" "${result}")
    # CMake OBJECT_OUTPUTS creates a Ninja phony alias, which does not rebuild
    # a missing side effect. A depfile edge makes a missing result
    # dirty its owning object. Ninja records command start time, so the result
    # must inherit an input timestamp instead of its later creation time.
    if(CMAKE_HOST_WIN32)
        execute_process(COMMAND powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass
            -File "${CMAKE_CURRENT_LIST_DIR}/declang_timestamp.ps1" -Source "${source}" -Result "${result}"
            RESULT_VARIABLE status)
    else()
        execute_process(COMMAND /usr/bin/touch -r "${source}" "${result}" RESULT_VARIABLE status)
    endif()
    if(NOT status STREQUAL "0")
        file(REMOVE "${result}")
        message(FATAL_ERROR "Cannot synchronize DeClang result timestamp")
    endif()
    foreach(variable object result)
        string(REPLACE "\\" "\\\\" escaped_${variable} "${${variable}}")
        string(REPLACE " " "\\ " escaped_${variable} "${escaped_${variable}}")
        string(REPLACE "#" "\\#" escaped_${variable} "${escaped_${variable}}")
        string(REPLACE "$" "$$" escaped_${variable} "${escaped_${variable}}")
    endforeach()
    file(APPEND "${depfile}" "\n${escaped_object}: ${escaped_result}\n")
endif()
