# DeClang's configuration reader uses the Windows CRT's bounded path API.
function(dn2cpp_declang_home requested output)
    set(home "${requested}")
    if(CMAKE_HOST_WIN32)
        file(TO_CMAKE_PATH "$ENV{TEMP}" temp)
        if(NOT IS_DIRECTORY "${temp}")
            message(FATAL_ERROR "DeClang requires an existing Windows TEMP directory")
        endif()
        get_filename_component(absolute "${requested}" ABSOLUTE)
        string(SHA256 key "${absolute}")
        set(home "${temp}/dn2cpp-declang/${key}")
        string(LENGTH "${home}/.DeClang/config.json" length)
        if(length GREATER_EQUAL 260)
            message(FATAL_ERROR "DeClang requires a shorter Windows TEMP path")
        endif()
    endif()
    file(MAKE_DIRECTORY "${home}/.DeClang")
    set(${output} "${home}" PARENT_SCOPE)
endfunction()
