set(DN2CPP_DECLANG_CONFIG "" CACHE FILEPATH "DeClang target manifest with per-function seeds")
if(NOT DN2CPP_DECLANG_CONFIG)
    return()
endif()
if(CMAKE_VERSION VERSION_LESS 3.21)
    message(FATAL_ERROR "DeClang requires CMake 3.21 for isolated linker launchers")
endif()
set(DN2CPP_DECLANG_ANDROID FALSE)
if(CMAKE_SYSTEM_NAME STREQUAL "Android")
    file(REAL_PATH "${CMAKE_TOOLCHAIN_FILE}" _declang_toolchain)
    file(REAL_PATH "${CMAKE_CURRENT_LIST_DIR}/android-declang.toolchain.cmake" _declang_expected_toolchain)
    if(NOT _declang_toolchain STREQUAL _declang_expected_toolchain OR NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin" OR NOT ANDROID_ABI STREQUAL "arm64-v8a" OR NOT CMAKE_C_COMPILER STREQUAL DN2CPP_DECLANG_COMPILER OR NOT CMAKE_CXX_COMPILER STREQUAL DN2CPP_DECLANG_COMPILER)
        message(FATAL_ERROR "Android DeClang requires its toolchain and selected compiler for arm64-v8a on macOS")
    endif()
    set(DN2CPP_DECLANG_ANDROID TRUE)
endif()
if(NOT CMAKE_GENERATOR STREQUAL "Ninja" OR (NOT DN2CPP_DECLANG_ANDROID AND (NOT APPLE OR CMAKE_CROSSCOMPILING)))
    message(FATAL_ERROR "DeClang requires Ninja and native macOS or the Android DeClang toolchain")
endif()
if(CMAKE_UNITY_BUILD)
    message(FATAL_ERROR "DeClang does not support Unity builds: application results require one invocation per generated translation unit")
endif()
if(DN2CPP_RUNTIME_EXPORT)
    message(FATAL_ERROR "DeClang cannot reuse a prebuilt runtime")
endif()
foreach(language C CXX)
    if(CMAKE_${language}_COMPILER_LAUNCHER AND NOT (DN2CPP_DECLANG_ANDROID AND CMAKE_${language}_COMPILER_LAUNCHER STREQUAL DN2CPP_DECLANG_DISABLED_LAUNCHER))
        message(FATAL_ERROR "DeClang does not support ccache, sccache, or other compiler launchers")
    endif()
endforeach()
get_cmake_property(_declang_variables VARIABLES)
foreach(variable IN LISTS _declang_variables)
    if(variable MATCHES "FLAGS|INTERPROCEDURAL_OPTIMIZATION")
        if("${${variable}}" MATCHES "-flto" OR (variable MATCHES "INTERPROCEDURAL_OPTIMIZATION" AND ${variable}))
            message(FATAL_ERROR "DeClang does not support LTO (${variable})")
        endif()
    endif()
endforeach()
if(NOT EXISTS "${DN2CPP_DECLANG_CONFIG}")
    message(FATAL_ERROR "DeClang configuration is missing: ${DN2CPP_DECLANG_CONFIG}")
endif()
set(_declang_work "${CMAKE_BINARY_DIR}/declang")
file(MAKE_DIRECTORY "${_declang_work}/disabled/.DeClang")
file(WRITE "${_declang_work}/disabled/.DeClang/config.json" "{\"enable_obfuscation\":0}\n")
set(ENV{DECLANG_HOME} "${_declang_work}/disabled")
if(DN2CPP_DECLANG_ANDROID)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DCOMPILER=${DN2CPP_DECLANG_COMPILER}" "-DWORK_DIR=${_declang_work}/compatibility" "-DNINJA_EXE=${CMAKE_MAKE_PROGRAM}" "-DANDROID_NDK=${ANDROID_NDK}" "-DANDROID_ABI=${ANDROID_ABI}" "-DANDROID_PLATFORM=${ANDROID_PLATFORM}" "-DANDROID_STL=${ANDROID_STL}" -P "${CMAKE_CURRENT_LIST_DIR}/declang_probe.cmake" RESULT_VARIABLE _declang_probe_status)
    if(NOT _declang_probe_status STREQUAL "0")
        message(FATAL_ERROR "Android DeClang compatibility probe failed")
    endif()
    file(READ "${_declang_work}/compatibility/identity.txt" _declang_identity)
    # The identity changes every compile command, including runtime objects and
    # PCH, when the compiler, its resources, or NDK inputs change.
    add_compile_definitions("DN2CPP_DECLANG_TOOLCHAIN_ID=${_declang_identity}")
    file(GLOB_RECURSE _declang_inputs CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE "${ANDROID_TOOLCHAIN_ROOT}/lib/clang/*" "${ANDROID_TOOLCHAIN_ROOT}/sysroot/usr/include/*" "${ANDROID_TOOLCHAIN_ROOT}/sysroot/usr/lib/aarch64-linux-android/*" "${ANDROID_NDK}/build/cmake/*")
    execute_process(COMMAND "${DN2CPP_DECLANG_COMPILER}" -print-resource-dir OUTPUT_VARIABLE _declang_resources OUTPUT_STRIP_TRAILING_WHITESPACE)
    file(GLOB_RECURSE _declang_resource_inputs CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE "${_declang_resources}/*")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${DN2CPP_DECLANG_COMPILER}" "${ANDROID_NDK}/source.properties" "${CMAKE_CURRENT_LIST_DIR}/declang_probe.cmake" "${CMAKE_CURRENT_LIST_DIR}/declang_launcher.cmake" "${CMAKE_CURRENT_LIST_DIR}/android-declang.toolchain.cmake" "${CMAKE_CURRENT_LIST_DIR}/declang_android_link.cmake" ${_declang_inputs} ${_declang_resource_inputs})
    foreach(tool clang clang++ ld.lld llvm-ar llvm-ranlib llvm-readelf llvm-strip)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ANDROID_TOOLCHAIN_ROOT}/bin/${tool}")
    endforeach()
endif()
set(_declang_launcher "${CMAKE_CURRENT_LIST_DIR}/declang_launcher.cmake")
set(CMAKE_C_COMPILER_LAUNCHER "${CMAKE_COMMAND};-DCONFIG=${DN2CPP_DECLANG_CONFIG};-DAPP_DIR=${DN2CPP_APP_DIR};-DWORK_DIR=${_declang_work};-P;${_declang_launcher};--")
set(CMAKE_CXX_COMPILER_LAUNCHER "${CMAKE_C_COMPILER_LAUNCHER}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${DN2CPP_DECLANG_CONFIG}")
function(dn2cpp_declang_sources)
    foreach(source IN LISTS DN2CPP_APP_SRCS)
        set_property(SOURCE "${source}" APPEND PROPERTY OBJECT_DEPENDS "${DN2CPP_DECLANG_CONFIG}" "${_declang_launcher}")
    endforeach()
endfunction()
file(READ "${DN2CPP_DECLANG_CONFIG}" _declang_manifest)
string(JSON _declang_version GET "${_declang_manifest}" version)
string(JSON _declang_count LENGTH "${_declang_manifest}" targets)
if(NOT _declang_version EQUAL 1 OR _declang_count EQUAL 0)
    message(FATAL_ERROR "DeClang requires a version 1 manifest with reachable targets")
endif()
math(EXPR _declang_end "${_declang_count} - 1")
foreach(i RANGE 0 ${_declang_end})
    string(JSON cpp GET "${_declang_manifest}" targets ${i} cppFile)
    if(NOT cpp MATCHES "^generated[A-Za-z0-9_]*\\.cpp$" OR NOT EXISTS "${DN2CPP_APP_DIR}/${cpp}")
        message(FATAL_ERROR "DeClang target does not name a generated translation unit: ${cpp}")
    endif()
endforeach()
foreach(arch IN LISTS CMAKE_OSX_ARCHITECTURES)
    if(NOT arch STREQUAL CMAKE_HOST_SYSTEM_PROCESSOR)
        message(FATAL_ERROR "DeClang requires the host architecture: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
    endif()
endforeach()
# Linking has no selected bodies, including when invoked outside the exporter.
if(NOT DN2CPP_DECLANG_ANDROID)
    set(CMAKE_C_LINKER_LAUNCHER "${CMAKE_COMMAND};-E;env;DECLANG_HOME=${_declang_work}/disabled")
    set(CMAKE_CXX_LINKER_LAUNCHER "${CMAKE_C_LINKER_LAUNCHER}")
endif()
