# dn2cpp_embed_bytes.cmake — turn a data file into a C++ translation unit that
# defines its bytes as a `const unsigned char[]` plus a length.
#
# Run as a script, not included:
#   cmake -DIN=<input file> -DOUT=<output .cpp> -DSYM=<C identifier> -P this
#
# Why a generated TU rather than reading the file at run time: the one consumer
# is the CA bundle the TLS backend needs (runtime/CMakeLists.txt's
# DN2CPP_USE_CURL arm), and a *file* is not something every dn2cpp target has.
# An Android APK, an iOS bundle and a wasm module each carry their payload
# differently and none of them is a path `fopen` can reach the way a desktop
# build can — so the bytes ride in the binary's own rodata, which is the one
# shape that is identical on every platform this project targets.
#
# The output is a build artifact and is written under the build tree: nothing
# here is meant to be committed. It regenerates whenever IN or this script
# changes (the add_custom_command DEPENDS at the call site).

if(NOT DEFINED IN OR NOT DEFINED OUT OR NOT DEFINED SYM)
    message(FATAL_ERROR "dn2cpp_embed_bytes.cmake: -DIN=, -DOUT= and -DSYM= are all required")
endif()
if(NOT EXISTS "${IN}")
    message(FATAL_ERROR "dn2cpp_embed_bytes.cmake: input does not exist: ${IN}")
endif()

# HEX, not a string read: the input is treated as opaque bytes, so nothing here
# has to reason about encodings, embedded NULs or escaping. A `0x..,` per byte
# also sidesteps MSVC's per-string-literal size ceiling (C2026), which a
# 180 KB string literal would walk straight into.
file(READ "${IN}" _dn2cpp_hex HEX)
string(LENGTH "${_dn2cpp_hex}" _dn2cpp_hexlen)
math(EXPR _dn2cpp_len "${_dn2cpp_hexlen} / 2")
if(_dn2cpp_len EQUAL 0)
    message(FATAL_ERROR "dn2cpp_embed_bytes.cmake: input is empty: ${IN}")
endif()

string(REGEX REPLACE "(..)" "0x\\1," _dn2cpp_bytes "${_dn2cpp_hex}")
# Break every 16 bytes so the emitted TU is a normal-looking source file rather
# than one multi-megabyte line (some editors and some preprocessors have a line
# length limit; none of them needs to be discovered the hard way). The sixteen
# groups are written out because CMake's regex flavour has no bounded-repetition
# operator — a `{16}` here matches the literal characters and silently does
# nothing, which is exactly the kind of no-op that looks like it worked.
string(REGEX REPLACE
    "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)"
    "\\1\n    " _dn2cpp_bytes "${_dn2cpp_bytes}")

get_filename_component(_dn2cpp_in_name "${IN}" NAME)
# `extern "C"` on both symbols: a gate reads them out of the object's own symbol
# table BY NAME, and only C linkage spells that name the same on every toolchain
# (MSVC decorates a C++ variable; the Itanium ABI leaves a global one alone).
file(WRITE "${OUT}"
"// GENERATED by runtime/cmake/dn2cpp_embed_bytes.cmake from ${_dn2cpp_in_name} —
// do not edit, do not commit. Regenerated by the build whenever the input moves.
extern \"C\" const unsigned char ${SYM}[] = {
    ${_dn2cpp_bytes}
};
extern \"C\" const unsigned int ${SYM}_len = ${_dn2cpp_len}u;
")
