set(DN2CPP_DECLANG_CONFIG "" CACHE FILEPATH "DeClang target manifest with per-function seeds")
if(NOT DN2CPP_DECLANG_CONFIG)
    return()
endif()
if(CMAKE_VERSION VERSION_LESS 3.21)
    message(FATAL_ERROR "DeClang requires CMake 3.21 for isolated linker launchers")
endif()
if(NOT APPLE OR CMAKE_CROSSCOMPILING OR NOT CMAKE_GENERATOR STREQUAL "Ninja")
    message(FATAL_ERROR "DeClang requires a native macOS build with Ninja")
endif()
if(CMAKE_UNITY_BUILD)
    message(FATAL_ERROR "DeClang does not support Unity builds: application results require one invocation per generated translation unit")
endif()
if(DN2CPP_RUNTIME_EXPORT)
    message(FATAL_ERROR "DeClang cannot reuse a prebuilt runtime")
endif()
if(CMAKE_C_COMPILER_LAUNCHER OR CMAKE_CXX_COMPILER_LAUNCHER)
    message(FATAL_ERROR "DeClang does not support ccache, sccache, or other compiler launchers")
endif()
get_cmake_property(_declang_variables VARIABLES)
foreach(variable IN LISTS _declang_variables)
    if(variable MATCHES "FLAGS|INTERPROCEDURAL_OPTIMIZATION")
        if("${${variable}}" MATCHES "-flto" OR (variable MATCHES "INTERPROCEDURAL_OPTIMIZATION" AND ${variable}))
            message(FATAL_ERROR "DeClang does not support LTO (${variable})")
        endif()
    endif()
endforeach()
if(NOT EXISTS "${DN2CPP_DECLANG_CONFIG}")
    message(FATAL_ERROR "DeClang configuration is missing: ${DN2CPP_DECLANG_CONFIG}")
endif()
set(_declang_work "${CMAKE_BINARY_DIR}/declang")
file(MAKE_DIRECTORY "${_declang_work}/disabled/.DeClang")
file(WRITE "${_declang_work}/disabled/.DeClang/config.json" "{\"enable_obfuscation\":0}\n")
set(ENV{DECLANG_HOME} "${_declang_work}/disabled")
set(_declang_launcher "${CMAKE_CURRENT_LIST_DIR}/declang_launcher.cmake")
set(CMAKE_C_COMPILER_LAUNCHER "${CMAKE_COMMAND};-DCONFIG=${DN2CPP_DECLANG_CONFIG};-DAPP_DIR=${DN2CPP_APP_DIR};-DWORK_DIR=${_declang_work};-P;${_declang_launcher};--")
set(CMAKE_CXX_COMPILER_LAUNCHER "${CMAKE_C_COMPILER_LAUNCHER}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${DN2CPP_DECLANG_CONFIG}")
function(dn2cpp_declang_sources)
    foreach(source IN LISTS DN2CPP_APP_SRCS)
        set_property(SOURCE "${source}" APPEND PROPERTY OBJECT_DEPENDS "${DN2CPP_DECLANG_CONFIG}" "${_declang_launcher}")
    endforeach()
endfunction()
file(READ "${DN2CPP_DECLANG_CONFIG}" _declang_manifest)
string(JSON _declang_version GET "${_declang_manifest}" version)
string(JSON _declang_count LENGTH "${_declang_manifest}" targets)
if(NOT _declang_version EQUAL 1 OR _declang_count EQUAL 0)
    message(FATAL_ERROR "DeClang requires a version 1 manifest with reachable targets")
endif()
math(EXPR _declang_end "${_declang_count} - 1")
foreach(i RANGE 0 ${_declang_end})
    string(JSON cpp GET "${_declang_manifest}" targets ${i} cppFile)
    if(NOT cpp MATCHES "^generated[A-Za-z0-9_]*\\.cpp$" OR NOT EXISTS "${DN2CPP_APP_DIR}/${cpp}")
        message(FATAL_ERROR "DeClang target does not name a generated translation unit: ${cpp}")
    endif()
endforeach()
foreach(arch IN LISTS CMAKE_OSX_ARCHITECTURES)
    if(NOT arch STREQUAL CMAKE_HOST_SYSTEM_PROCESSOR)
        message(FATAL_ERROR "DeClang requires the host architecture: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
    endif()
endforeach()
# Linking has no selected bodies, including when invoked outside the exporter.
set(CMAKE_C_LINKER_LAUNCHER "${CMAKE_COMMAND};-E;env;DECLANG_HOME=${_declang_work}/disabled")
set(CMAKE_CXX_LINKER_LAUNCHER "${CMAKE_C_LINKER_LAUNCHER}")
