<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <NoWarn>CA2255</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BootstrapFixture/BootstrapFixture.csproj" />
  </ItemGroup>
</Project>
