<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(DefineConstants);METHOD_BODY_NEEDED</DefineConstants>
    <AssemblyName>ReflectionMethodBodyNeeded</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../AppDependencies/Program.cs" Link="Program.cs" />
    <ProjectReference Include="../Ext/Ext.csproj" />
    <ProjectReference Include="../Lib/Lib.csproj" />
  </ItemGroup>
</Project>
